In [1]:
from cosecha_colectiva import miscelaneous as m
import pandas as pd
m.try_find_conf_file()


from cosecha_colectiva import main_tester as mt
from cosecha_colectiva import config
from cosecha_colectiva import query_cosecha as qc
from cosecha_colectiva import test_cosecha_api as tca
from cosecha_colectiva import CAF_DB_Monitor as CDM

from cosecha_colectiva import miscelaneous as m



import logging
import pathlib
from datetime import datetime, date
from dateutil.relativedelta import relativedelta

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

Local configuration file found !!, no need to run the configuration (unless configuration has changed)

c:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\.venv\Lib\site-packages\datajoint\plugin.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-04-08 12:38:03,094][INFO]: DataJoint 0.14.6 connected to root@junction.proxy.rlwy.net:19994

In [2]:
now = datetime.now()
log_date = now.strftime("%Y-%m-%d_%H_%M_%S")
log_file = pathlib.Path(config.log_dir, log_date+'CreacionGrupo.log')
logging.basicConfig(filename=log_file, encoding='utf-8', level=logging.INFO)

In [3]:
xls_name = 'Verde_Futuro_Test.xlsx'
xls_name = 'Verde_Futuro.xlsx'

xls_name = 'Tropa Gusgones_2.0.xlsx'
xls_name = 'Tropa Gusgones_2.0_Test.xlsx'

xls_name = 'Alcancía Viva.xlsx'
#xls_name = 'Alcancía Viva Test.xlsx'

xls_name = 'Licenciados_Asociados.xlsx'
#xls_name = 'Licenciados_Asociados_Test.xlsx'

xls_name = 'Juntas_ahorramos.xlsx'
xls_name = 'Juntes_ahorramos.xlsx'


xls_name = 'Procoseq.xlsx'

xls_name = 'CAFAM.xlsx'

xls_name = 'La Colmena.xlsx'

xls_name = 'Caja ahorro magueyeros.xlsx'

xls_name = 'Caja la llave.xlsx'

xls_name = 'Agrosemilla sin varo'

xls_name = 'Alcancía Viva.xlsx'

xls_name = 'Caja llanitos Hidalgo'
#xls_name = 'Juntos_ahorramos.xlsx'



#xls_name = 'CAF_GrupoTest.xlsx'
#xls_name = 'CAF_GrupoHidalgo.xlsx'
#xls_name = 'GrupoCafam.xlsx'

#xls_name = 'Yeiyei'

In [4]:
xls_name

'Caja llanitos Hidalgo'

In [5]:
[id_grupo, grupo_found] = qc.get_grupo_id_by_name(xls_name.replace(".xlsx", ""))
print(id_grupo)
print(grupo_found)
#qc.delete_grupo(id_grupo, solo_sesiones=True)
#qc.delete_grupo(id_grupo)

2622
True

In [6]:
if not grupo_found:
    grupo_data = m.read_caf_excel_sheet(pathlib.Path(xls_name), 'Grupo')
    id_grupo = qc.insert_grupo(grupo_data.to_dict('records'))
    id_grupo = id_grupo['Grupo_id']
    
id_grupo

np.int64(2622)

In [7]:
if not grupo_found:

    socios_xls = pd.DataFrame(m.get_dict_usuarios_xls(xls_name))
    # Solo crea socios cuando viene los datos completos
    if not socios_xls['Fecha_nac'].isna().all():
        print('Creando usuarios')
        tca.CAF_API_group_creation_tester.create_users(xls_name)

    grupo_socio_df = qc.prepare_insert_socio_grupo(xls_name, id_grupo)

    df_acuerdos = m.read_caf_excel_sheet(pathlib.Path(xls_name), "Acuerdos")
    df_acuerdos['Grupo_id'] = id_grupo
    df_acuerdos['Fecha_acuerdos'] = datetime.strftime(date.today(), format='%Y-%m-%d')
    df_acuerdos['Status'] = 1

    df_acuerdos['Id_socio_administrador'] = grupo_socio_df.loc[0,'Socio_id']
    df_acuerdos['Id_socio_administrador_suplente'] = grupo_socio_df.loc[1,'Socio_id']

    qc.insert_acuerdos(df_acuerdos.to_dict('records')[0])

In [8]:
start_month = 3
end_month = 3
last_fecha = qc.get_last_fecha_sesion_grupo(id_grupo)
initial_date = (last_fecha[0]['Fecha'] + relativedelta(months=end_month))
initial_date = (last_fecha[0]['Fecha'] + relativedelta(months=0))
initial_date

datetime.date(2025, 12, 19)

In [9]:

monitor_grupo = CDM.CAF_DB_Monitor(id_grupo, xls_name, starting_date=initial_date)
monitor_grupo.socios_acciones

,Grupo_socio_id,Socio_id,Tipo_socio,Status,Acciones,Grupo_id,CURP,xls_order
0,9103,3048,SOCIO,1,3210,2622,MARA770221HQTRSN06,0
1,9104,3049,SOCIO,1,2100,2622,MAHA520412HQTRRN08,1
2,9143,3082,SUPLENTE,1,2800,2622,MARA810811HQTRSL00,2
3,9144,3081,ADMIN,1,2700,2622,MAGL000106MQTRRZA3,3
4,9145,3083,SOCIO,1,2050,2622,MARL030823MQTRSLA3,4
5,9146,3084,SOCIO,1,2000,2622,MAGA160705HQTRRLA2,5
6,9147,3085,SOCIO,1,3300,2622,MARC050924HQTRSRA1,6
7,9148,3080,SOCIO,1,2500,2622,MARM891205MQTRSR03,7
8,9151,3088,SOCIO,1,3200,2622,MOLC890619MJCRRN05,8
9,9153,3091,SOCIO,1,2900,2622,MARA880126HQTRSM08,9
10,9159,3096,SOCIO,1,1600,2622,MOLL910328MJCRRR15,10
11,9160,3097,SOCIO,1,1500,2622,LAMI701017MJCRRD05,11
12,9165,3098,SOCIO,1,300,2622,BESA980930HJCCRN09,12
13,9166,3099,SOCIO,1,1100,2622,MOLJ011219MJCRRNB6,13

In [13]:
int(monitor_grupo.sesiones[-1]['Sesion_id'])

20077

In [11]:
prestamos_activos = monitor_grupo.prestamos.loc[monitor_grupo.prestamos['Estatus_prestamo']==0,:]
prestamos_activos

,Prestamo_id,Acuerdos_id,Monto_prestamo,Monto_pagado,Interes_generado,Interes_pagado,Fecha_inicial,Fecha_final,Estatus_ampliacion,Observaciones,Num_sesiones,Sesiones_restantes,Estatus_prestamo,Socio_id,Sesion_id,Prestamo_original_id,Grupo_id,Tasa_interes,Limite_credito,Creditos_simultaneos,Interes_morosidad,Ampliacion_prestamos,Interes_ampliacion,Mod_calculo_interes,Tasa_interes_prestamo_grande,Grupo_socio_id,Status_socio,interes_futuro,Ultimo_interes_pagado,debe_interes,sobrante_abono,Ultimo_abono
1,6680,2257,5100.0,2500.0,51.0,51.0,2025-10-26,2026-04-26,0,,6,4,0,3081,19905,None,2622,1.0,3,1,2.0,1,1.0,1,NaN,9144,1,51.0,0,0,0,0
2,6881,2257,5000.0,0.0,0.0,0.0,2025-11-19,2026-05-19,0,Préstamo generado en script automático,6,6,0,3083,20076,None,2622,1.0,3,1,2.0,1,1.0,1,NaN,9145,1,50.0,0,0,0,0
3,6882,2257,2500.0,0.0,0.0,0.0,2025-11-19,2026-04-19,0,Préstamo generado en script automático,5,5,0,3084,20076,None,2622,1.0,3,1,2.0,1,1.0,1,NaN,9146,1,25.0,0,0,0,0

In [12]:
monitor_grupo.caja

15778.0

In [13]:

for month in range(start_month, end_month+1):

    print('month: ', month)

    try:
        monitor_grupo.actualiza_todo_sesion(xls_name, month, type_xls='NEW', bd_update=True, unique_session_to_update=False)
    except Exception as e:
        print(e)
        raise(e)
        break

month:  2

C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:287: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  prestamos_activos.loc[prestamos_activos['sobrante_abono'] < 0, 'Interes_pagado'] =\
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:294: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  prestamos_activos.loc[prestamos_activos['sobrante_abono'] < 0, 'Ultimo_interes_pagado'] =\
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:311: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[102.0 50.0 25.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  self.prestamos.loc[prestamos_activos.index] = prestamos_activos
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:311: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[51 50 25]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.prestamos.loc[prestamos_activos.index] = prestamos_activos
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:311: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[2651.0 551.0 2525.0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.prestamos.loc[prestamos_activos.index] = prestamos_activos

df_prestamos in actualiza prestamos
          PRÉSTAMO AMPLIACIÓN NUM_SESIONES
Socio_id
3048      [9000.0]        [0]         [12]
ganancias_totales_sesion
126
ganancias_totales_floor
122.0
sob_acciones
8.0
ganancias_sesion
    Acciones  Socio_id  Monto_ganancia_floor  sobrante_Monto_ganancia  \
0        300      3098                   1.0                      0.5
1       1100      3099                   4.0                      0.5
2       1500      3097                   6.0                      0.5
3       1600      3096                   6.0                      0.5
4       2000      3084                   8.0                      0.5
5       2050      3083                   8.0                      0.5
6       2100      3049                   8.0                      0.5
7       2500      3080                  10.0                      0.5
8       2700      3081                  10.5                      0.0
9       2800      3082                  11.0                      0.0
10      2900      3091                  11.5                      0.0
11      3200      3088                  12.5                      0.0
12      3210      3048                  12.5                      0.0
13      3300      3085                  13.0                      0.0

    Monto_ganancia  Entregada  Sesion_id  Ganancias_id  Ganancia_accion  \
0              1.5          0      20077         -1000         0.004031
1              4.5          0      20077          -999         0.004031
2              6.5          0      20077          -998         0.004031
3              6.5          0      20077          -997         0.004031
4              8.5          0      20077          -996         0.004031
5              8.5          0      20077          -995         0.004031
6              8.5          0      20077          -994         0.004031
7             10.5          0      20077          -993         0.004031
8             10.5          0      20077          -992         0.004031
9             11.0          0      20077          -991         0.004031
10            11.5          0      20077          -990         0.004031
11            12.5          0      20077          -989         0.004031
12            12.5          0      20077          -988         0.004031
13            13.0          0      20077          -987         0.004031

   periodo
0    nuevo
1    nuevo
2    nuevo
3    nuevo
4    nuevo
5    nuevo
6    nuevo
7    nuevo
8    nuevo
9    nuevo
10   nuevo
11   nuevo
12   nuevo
13   nuevo

In [14]:
monitor_grupo.prestamos

,Prestamo_id,Acuerdos_id,Monto_prestamo,Monto_pagado,Interes_generado,Interes_pagado,Fecha_inicial,Fecha_final,Estatus_ampliacion,Observaciones,Num_sesiones,Sesiones_restantes,Estatus_prestamo,Socio_id,Sesion_id,Prestamo_original_id,Grupo_id,Tasa_interes,Limite_credito,Creditos_simultaneos,Interes_morosidad,Ampliacion_prestamos,Interes_ampliacion,Mod_calculo_interes,Tasa_interes_prestamo_grande,Grupo_socio_id,Status_socio,interes_futuro,Ultimo_interes_pagado,debe_interes,sobrante_abono,Ultimo_abono
0,6637,2257,3900.0,3900.0,117.0,117.0,2025-08-26,2026-01-26,0,,5,1,1,3048,19888,None,2622,1.0,3,1,2.0,1,1.0,1,NaN,9103.0,1,0.0,0.0,0,0,0.0
1,6680,2257,5100.0,5100.0,102.0,102.0,2025-10-26,2026-04-26,0,,6,3,1,3081,19905,None,2622,1.0,3,1,2.0,1,1.0,1,NaN,9144.0,1,0.0,0.0,0,0,0.0
2,6881,2257,5000.0,501.0,50.0,50.0,2025-11-19,2026-05-19,0,Préstamo generado en script automático,6,5,0,3083,20076,None,2622,1.0,3,1,2.0,1,1.0,1,NaN,9145.0,1,50.0,50,50,501,551.0
3,6882,2257,2500.0,2500.0,25.0,25.0,2025-11-19,2026-04-19,0,Préstamo generado en script automático,5,4,1,3084,20076,None,2622,1.0,3,1,2.0,1,1.0,1,NaN,9146.0,1,0.0,0.0,0,0,0.0
4,6883,2257,9000.0,0.0,0.0,0,2026-01-19,2027-01-19,0,Préstamo generado en script automático,12,12,0,3048,20077,None,2622,1.0,3,1,2.0,1,1.0,1,None,NaN,1,90.0,0,0,0,0

In [15]:
monitor_grupo.caja

np.float64(18055.0)

In [15]:
monitor_grupo.caja

np.float64(5831.5)

In [16]:
monitor_grupo.ganancias

,Ganancias_id,Ganancia_accion,Monto_ganancia,Entregada,Socio_id,Sesion_id,periodo
0,79667,0.000000,0.0,1,2934,19741,nuevo
1,79668,0.000000,0.0,1,2924,19741,nuevo
2,79669,0.000000,0.0,1,2914,19741,nuevo
3,79670,0.000000,0.0,1,2904,19741,nuevo
4,79671,0.000000,0.0,1,2894,19741,nuevo
...,...,...,...,...,...,...,...
65,81316,0.018079,16.5,0,2924,20074,nuevo
66,81317,0.018079,17.5,0,2904,20074,nuevo
67,81318,0.018079,18.5,0,2914,20074,nuevo
68,81319,0.018079,19.5,0,2894,20074,nuevo
69,81320,0.018079,24.0,0,2934,20074,nuevo

In [17]:
monitor_grupo.multas

,Multa_id,Monto_multa,Descripcion,Status,Sesion_id,Socio_id,Transaccion_id,created_at,Pago_en_sesion
0,3539,5.0,Multa # 1 socio 2894 grupo: 2574 con script,1,19741,2894,39501,2024-12-27 00:00:00,0
1,3570,20.0,Falta justificada,1,19797,2914,39471,2025-03-27 21:36:52,0
2,3571,20.0,Falta justificada,1,19797,2934,39472,2025-03-27 21:37:10,0
3,3589,7.0,Retraso de inicio,1,19860,2924,39833,2025-06-30 19:15:55,0
4,3601,15.0,15 pesos por retraso,1,19889,2934,39905,2025-08-29 20:28:14,0
5,3608,20.0,falta justificada,1,19894,2914,40054,2025-09-26 20:12:51,0

In [18]:
monitor_grupo.acuerdos

Acuerdo_id                                      2270
Id_temporal_admin                               None
id_treasurer_user                               None
id_secretary_user                               None
allow_action_retreat_on_normal_session             0
Grupo_id                                        2574
Fecha_acuerdos                            2025-07-01
Fecha_acuerdos_fin                        2026-02-01
Status                                             1
Periodo_reuniones                                  3
Periodo_cargos                                     1
Limite_inasistencias                               3
Minimo_aportacion                                100
Costo_acciones                                    10
Tasa_interes                                     6.0
Limite_credito                                     4
Porcentaje_fondo_comun                             0
Creditos_simultaneos                               1
Interes_morosidad                                2.0
Ampliacion_prestamos                               0
Interes_ampliacion                              None
Mod_calculo_interes                                1
Tasa_interes_prestamo_grande                     0.0
Id_socio_administrador                          2894
Id_socio_administrador_suplente                 2924
dtype: object

In [19]:
monitor_grupo.ganancias_acum.sum()

Monto_ganancia    96.0
dtype: float64

In [20]:
monitor_grupo.multas

,Multa_id,Monto_multa,Descripcion,Status,Sesion_id,Socio_id,Transaccion_id,created_at,Pago_en_sesion
0,3539,5.0,Multa # 1 socio 2894 grupo: 2574 con script,1,19741,2894,39501,2024-12-27 00:00:00,0
1,3570,20.0,Falta justificada,1,19797,2914,39471,2025-03-27 21:36:52,0
2,3571,20.0,Falta justificada,1,19797,2934,39472,2025-03-27 21:37:10,0
3,3589,7.0,Retraso de inicio,1,19860,2924,39833,2025-06-30 19:15:55,0
4,3601,15.0,15 pesos por retraso,1,19889,2934,39905,2025-08-29 20:28:14,0
5,3608,20.0,falta justificada,1,19894,2914,40054,2025-09-26 20:12:51,0

In [21]:
monitor_grupo.transacciones_prestamo_bd

,index,Transaccion_prestamo_id,Prestamo_id,Transaccion_id,Monto_abono_prestamo,Monto_abono_interes
0,0,11316,6827,41325,600.0,36
1,1,11317,6828,41326,500.0,30
2,2,11318,6829,41327,500.0,30

In [22]:
monitor_grupo.transacciones_bd

,Transaccion_id,Cantidad_movimiento,Caja,Timestamp,Sesion_id,Socio_id,Acuerdo_id,Catalogo_id,Prestamo_id,Ultimo_interes_pagado,sobrante_abono
0,41320,60,60,2026-03-07 00:00:00,20074,2934,2270,COMPRA_ACCION,NaN,NaN,NaN
1,41321,100,160,2026-03-07 00:00:00,20074,2924,2270,COMPRA_ACCION,NaN,NaN,NaN
2,41322,100,260,2026-03-07 00:00:00,20074,2914,2270,COMPRA_ACCION,NaN,NaN,NaN
3,41323,50,310,2026-03-07 00:00:00,20074,2904,2270,COMPRA_ACCION,NaN,NaN,NaN
4,41324,50,360,2026-03-07 00:00:00,20074,2894,2270,COMPRA_ACCION,NaN,NaN,NaN
5,41325,636.0,996.0,2026-03-07 00:00:00,20074,2914,2270,ABONO_PRESTAMO,6827.0,36,600.0
6,41326,530.0,1526.0,2026-03-07 00:00:00,20074,2894,2270,ABONO_PRESTAMO,6828.0,30,500.0
7,41327,530.0,2056.0,2026-03-07 00:00:00,20074,2934,2270,ABONO_PRESTAMO,6829.0,30,500.0
8,41328,-200.0,1856.0,2026-03-07 00:00:00,20074,2894,2270,ENTREGA_PRESTAMO,6879.0,NaN,NaN