In [1]:
from cosecha_colectiva import miscelaneous as m
import pandas as pd
m.try_find_conf_file()


from cosecha_colectiva import main_tester as mt
from cosecha_colectiva import config
from cosecha_colectiva import query_cosecha as qc
from cosecha_colectiva import test_cosecha_api as tca
from cosecha_colectiva import CAF_DB_Monitor as CDM

from cosecha_colectiva import miscelaneous as m

import logging
import pathlib
from datetime import datetime, date
from dateutil.relativedelta import relativedelta

Local configuration file found !!, no need to run the configuration (unless configuration has changed)

c:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\.venv\Lib\site-packages\datajoint\plugin.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-01-12 12:19:13,443][INFO]: DataJoint 0.14.6 connected to root@junction.proxy.rlwy.net:19994

In [2]:
now = datetime.now()
log_date = now.strftime("%Y-%m-%d_%H_%M_%S")
log_file = pathlib.Path(config.log_dir, log_date+'CreacionGrupo.log')
logging.basicConfig(filename=log_file, encoding='utf-8', level=logging.INFO)

In [3]:
xls_name = 'Verde_Futuro_Test.xlsx'
xls_name = 'Verde_Futuro.xlsx'

xls_name = 'Tropa Gusgones_2.0.xlsx'
xls_name = 'Tropa Gusgones_2.0_Test.xlsx'

xls_name = 'Alcancía Viva.xlsx'
#xls_name = 'Alcancía Viva Test.xlsx'

xls_name = 'Licenciados_Asociados.xlsx'
#xls_name = 'Licenciados_Asociados_Test.xlsx'

xls_name = 'Juntas_ahorramos.xlsx'
xls_name = 'Juntes_ahorramos.xlsx'


xls_name = 'Procoseq.xlsx'

xls_name = 'CAFAM.xlsx'

xls_name = 'La Colmena.xlsx'

#xls_name = 'Juntos_ahorramos.xlsx'



#xls_name = 'CAF_GrupoTest.xlsx'
#xls_name = 'CAF_GrupoHidalgo.xlsx'
#xls_name = 'GrupoCafam.xlsx'

#xls_name = 'Yeiyei'

In [4]:
xls_name

'La Colmena.xlsx'

In [20]:
[id_grupo, grupo_found] = qc.get_grupo_id_by_name(xls_name.replace(".xlsx", ""))
print(id_grupo)
print(grupo_found)
#qc.delete_grupo(id_grupo, solo_sesiones=True)
#qc.delete_grupo(id_grupo)

2651
True

In [21]:
if not grupo_found:
    grupo_data = m.read_caf_excel_sheet(pathlib.Path(xls_name), 'Grupo')
    id_grupo = qc.insert_grupo(grupo_data.to_dict('records'))
    id_grupo = id_grupo['Grupo_id']
    
id_grupo

np.int64(2651)

In [22]:
if not grupo_found:

    socios_xls = pd.DataFrame(m.get_dict_usuarios_xls(xls_name))
    # Solo crea socios cuando viene los datos completos
    if not socios_xls['Fecha_nac'].isna().all():
        print('Creando usuarios')
        tca.CAF_API_group_creation_tester.create_users(xls_name)

    grupo_socio_df = qc.prepare_insert_socio_grupo(xls_name, id_grupo)

    df_acuerdos = m.read_caf_excel_sheet(pathlib.Path(xls_name), "Acuerdos")
    df_acuerdos['Grupo_id'] = id_grupo
    df_acuerdos['Fecha_acuerdos'] = datetime.strftime(date.today(), format='%Y-%m-%d')
    df_acuerdos['Status'] = 1

    df_acuerdos['Id_socio_administrador'] = grupo_socio_df.loc[0,'Socio_id']
    df_acuerdos['Id_socio_administrador_suplente'] = grupo_socio_df.loc[1,'Socio_id']

    qc.insert_acuerdos(df_acuerdos.to_dict('records')[0])

In [23]:
qc.delete_grupo(id_grupo, solo_sesiones=True, force_delete=True, desde_sesion_0=True,conservar_acuerdos=True)


qc.restart_grupo_acciones(id_grupo, desde_sesion_0=True)

([{'Transaccion_prestamo_id': np.int64(11194)}, {'Transaccion_prestamo_id': np.int64(11195)}, {'Transaccion_prestamo_id': np.int64(11196)}, {'Transaccion_prestamo_id': np.int64(11197)}, {'Transaccion_prestamo_id': np.int64(11198)}, {'Transaccion_prestamo_id': np.int64(11199)}, {'Transaccion_prestamo_id': np.int64(11200)}, {'Transaccion_prestamo_id': np.int64(11201)}], 'transaccion_prestamos')
DELETE from railway.transaccion_prestamos WHERE Transaccion_prestamo_id in (11194, 11195, 11196, 11197, 11198, 11199, 11200, 11201)
([{'Transaccion_id': np.int64(40562)}, {'Transaccion_id': np.int64(40563)}, {'Transaccion_id': np.int64(40564)}, {'Transaccion_id': np.int64(40565)}, {'Transaccion_id': np.int64(40566)}, {'Transaccion_id': np.int64(40567)}, {'Transaccion_id': np.int64(40568)}, {'Transaccion_id': np.int64(40569)}, {'Transaccion_id': np.int64(40570)}, {'Transaccion_id': np.int64(40571)}, {'Transaccion_id': np.int64(40572)}, {'Transaccion_id': np.int64(40573)}, {'Transaccion_id': np.int64(40574)}, {'Transaccion_id': np.int64(40575)}, {'Transaccion_id': np.int64(40576)}, {'Transaccion_id': np.int64(40577)}, {'Transaccion_id': np.int64(40578)}, {'Transaccion_id': np.int64(40579)}, {'Transaccion_id': np.int64(40580)}, {'Transaccion_id': np.int64(40581)}, {'Transaccion_id': np.int64(40582)}, {'Transaccion_id': np.int64(40583)}, {'Transaccion_id': np.int64(40584)}, {'Transaccion_id': np.int64(40585)}, {'Transaccion_id': np.int64(40586)}, {'Transaccion_id': np.int64(40587)}], 'transacciones')
DELETE from railway.transacciones WHERE Transaccion_id in (40562, 40563, 40564, 40565, 40566, 40567, 40568, 40569, 40570, 40571, 40572, 40573, 40574, 40575, 40576, 40577, 40578, 40579, 40580, 40581, 40582, 40583, 40584, 40585, 40586, 40587)
([], 'interes_prestamo')
([{'Ganancias_id': np.int64(80731)}, {'Ganancias_id': np.int64(80732)}, {'Ganancias_id': np.int64(80733)}, {'Ganancias_id': np.int64(80734)}, {'Ganancias_id': np.int64(80735)}, {'Ganancias_id': np.int64(80736)}, {'Ganancias_id': np.int64(80737)}, {'Ganancias_id': np.int64(80738)}, {'Ganancias_id': np.int64(80739)}], 'ganancias')
DELETE from railway.ganancias WHERE Ganancias_id in (80731, 80732, 80733, 80734, 80735, 80736, 80737, 80738, 80739)
([], 'multas')
([], 'prestamos')
([{'Prestamo_id': np.int64(6803)}, {'Prestamo_id': np.int64(6804)}, {'Prestamo_id': np.int64(6805)}, {'Prestamo_id': np.int64(6806)}, {'Prestamo_id': np.int64(6807)}, {'Prestamo_id': np.int64(6808)}, {'Prestamo_id': np.int64(6809)}, {'Prestamo_id': np.int64(6810)}, {'Prestamo_id': np.int64(6811)}, {'Prestamo_id': np.int64(6812)}], 'prestamos')
DELETE from railway.prestamos WHERE Prestamo_id in (6803, 6804, 6805, 6806, 6807, 6808, 6809, 6810, 6811, 6812)
([{'Asistencia_id': np.int64(139259)}, {'Asistencia_id': np.int64(139260)}, {'Asistencia_id': np.int64(139261)}, {'Asistencia_id': np.int64(139262)}, {'Asistencia_id': np.int64(139263)}, {'Asistencia_id': np.int64(139264)}, {'Asistencia_id': np.int64(139265)}, {'Asistencia_id': np.int64(139266)}, {'Asistencia_id': np.int64(139267)}], 'asistencias')
DELETE from railway.asistencias WHERE Asistencia_id in (139259, 139260, 139261, 139262, 139263, 139264, 139265, 139266, 139267)
([{'Sesion_id': np.int64(19961)}], 'sesiones')
DELETE from railway.sesiones WHERE Sesion_id in (19961)
([], 'acuerdos')

In [24]:
start_month = 1
end_month = 1
initial_date = (date.today() - relativedelta(months=end_month))

monitor_grupo = CDM.CAF_DB_Monitor(id_grupo, xls_name, starting_date=initial_date)
monitor_grupo.socios_acciones

,Grupo_socio_id,Socio_id,Tipo_socio,Status,Acciones,Grupo_id,CURP,xls_order
0,9215,1704,ADMIN,1,0,2651,CAAM810218MMNHLY03,0
1,9216,3131,SOCIO,1,0,2651,CAAM810218MMNHLY04,1
2,9217,3132,SOCIO,1,0,2651,CAAM810218MMNHLY05,2
3,9218,3133,SUPLENTE,1,0,2651,RABC840919MQTMRL06,3
4,9219,3134,SOCIO,1,0,2651,CAAM810218MMNHLY07,4
5,9220,3135,SOCIO,1,0,2651,CAAM810218MMNHLY08,5
6,9221,3136,SOCIO,1,0,2651,TOOE890722MSPRTR02,6
7,9222,3137,SOCIO,1,0,2651,ROTN820917MMCJVD02,7
8,9223,3138,SOCIO,1,0,2651,CAAM810218MMNHLY10,8

In [25]:

for month in range(start_month, end_month+1):

    print('month: ', month)

    try:
        monitor_grupo.actualiza_todo_sesion(xls_name, month, type_xls='NEW', bd_update=True, unique_session_to_update=True)
    except Exception as e:
        print(e)
        raise(e)
        break

month:  1
   Socio_id GANANCIAS  Sesion_id
0      1704       5.0      19962
1      3131       5.0      19962
2      3132       5.0      19962
3      3133       5.0      19962
4      3134       5.0      19962
5      3135       5.0      19962
6      3136       5.0      19962
7      3137       5.0      19962
   Ganancias_id  Ganancia_accion  Monto_ganancia  Entregada  Socio_id  \
0         -1000              0.0             0.0          0      3138
1          -999              0.0             5.0          0      3137
2          -998              0.0             5.0          0      1704
3          -997              0.0             5.0          0      3134
4          -996              0.0             5.0          0      3136
5          -995              0.0             5.0          0      3135
6          -994              0.0             5.0          0      3132
7          -993              0.0             5.0          0      3131
8          -992              0.0             5.0          0      3133

   Sesion_id periodo
0      19962   nuevo
1      19962   nuevo
2      19962   nuevo
3      19962   nuevo
4      19962   nuevo
5      19962   nuevo
6      19962   nuevo
7      19962   nuevo
8      19962   nuevo

In [26]:
monitor_grupo.socios_acciones

,Grupo_socio_id,Socio_id,Grupo_id,Tipo_socio,Acciones,Status,CURP
0,9215,1704,2651,ADMIN,11380,1,CAAM810218MMNHLY03
1,9216,3131,2651,SOCIO,16840,1,CAAM810218MMNHLY04
2,9217,3132,2651,SOCIO,16840,1,CAAM810218MMNHLY05
3,9218,3133,2651,SUPLENTE,19850,1,RABC840919MQTMRL06
4,9219,3134,2651,SOCIO,12350,1,CAAM810218MMNHLY07
5,9220,3135,2651,SOCIO,14800,1,CAAM810218MMNHLY08
6,9221,3136,2651,SOCIO,12410,1,TOOE890722MSPRTR02
7,9222,3137,2651,SOCIO,9370,1,ROTN820917MMCJVD02
8,9223,3138,2651,SOCIO,0,1,CAAM810218MMNHLY10

In [27]:
monitor_grupo.prestamos

,Prestamo_id,Monto_prestamo,Monto_pagado,Interes_generado,Interes_pagado,Fecha_inicial,Fecha_final,Estatus_ampliacion,Observaciones,Num_sesiones,...,Ampliacion_prestamos,Interes_ampliacion,Mod_calculo_interes,Tasa_interes_prestamo_grande,interes_futuro,Ultimo_interes_pagado,debe_interes,sobrante_abono,Ultimo_abono,Status_socio
0,6813,30000.0,5522.0,0,0,2025-12-12,2027-09-12,False,Préstamo generado en script automático,21,...,0,0.0,1,1.5,250.0,0,0,5522.0,5522.0,1
1,6814,12000.0,8000.0,0,0,2025-12-12,2026-06-12,False,Préstamo generado en script automático,6,...,0,0.0,1,1.5,100.0,0,0,8000.0,8000.0,1
2,6815,5000.0,1458.5,0,0,2025-12-12,2026-06-12,False,Préstamo generado en script automático,6,...,0,0.0,1,1.5,41.5,0,0,1458.5,1458.5,1
3,6816,15000.0,9750.0,0,0,2025-12-12,2026-08-12,False,Préstamo generado en script automático,8,...,0,0.0,1,1.5,125.0,0,0,9750.0,9750.0,1
4,6817,7000.0,1749.0,0,0,2025-12-12,2026-06-12,False,Préstamo generado en script automático,6,...,0,0.0,1,1.5,58.5,0,0,1749.0,1749.0,1
5,6818,5000.0,834.0,0,0,2025-12-12,2026-10-12,False,Préstamo generado en script automático,10,...,0,0.0,1,1.5,41.5,0,0,834.0,834.0,1
6,6819,2501.0,2128.0,0,0,2025-12-12,2026-10-12,False,Préstamo generado en script automático,10,...,0,0.0,1,1.5,21.0,0,0,2128.0,2128.0,1
7,6820,500.0,0.0,0,0,2025-12-12,2026-11-12,False,Préstamo generado en script automático,11,...,0,0.0,1,1.5,4.0,0,0,0.0,0.0,1
8,6821,25000.0,0.0,0,0,2025-12-12,2028-12-12,False,Préstamo generado en script automático,36,...,0,0.0,1,1.5,208.5,0,0,0.0,0.0,1
9,6822,20050.0,1274.5,0,0,2025-12-12,2028-10-12,False,Préstamo generado en script automático,34,...,0,0.0,1,1.5,167.0,0,0,1274.5,1274.5,1

In [28]:
monitor_grupo.sesiones_bd

,Sesion_id,Fecha,Activa,Caja,Acciones,Ganancias,Fecha_prox_reunion,Lugar_prox_reunion,Tipo_sesion,Grupo_id,created_at
0,19962,2025-12-12,0,22505.0,113840,40.0,2026-01-12,Sesion creada en script,1,2651,2025-12-12

In [29]:
monitor_grupo.caja

np.float64(22505.0)

In [30]:
monitor_grupo.ganancias

,Ganancias_id,Ganancia_accion,Monto_ganancia,Entregada,Socio_id,Sesion_id,periodo
0,80740,0.0,0.0,0,3138,19962,nuevo
1,80741,0.0,5.0,0,3137,19962,nuevo
2,80742,0.0,5.0,0,1704,19962,nuevo
3,80743,0.0,5.0,0,3134,19962,nuevo
4,80744,0.0,5.0,0,3136,19962,nuevo
5,80745,0.0,5.0,0,3135,19962,nuevo
6,80746,0.0,5.0,0,3132,19962,nuevo
7,80747,0.0,5.0,0,3131,19962,nuevo
8,80748,0.0,5.0,0,3133,19962,nuevo

In [31]:
monitor_grupo.acuerdos

Acuerdo_id                                      2283
Id_temporal_admin                               None
id_treasurer_user                               None
id_secretary_user                               None
allow_action_retreat_on_normal_session             0
Grupo_id                                        2651
Fecha_acuerdos                            2026-01-11
Fecha_acuerdos_fin                        2026-11-10
Status                                             1
Periodo_reuniones                                  4
Periodo_cargos                                     4
Limite_inasistencias                               4
Minimo_aportacion                                100
Costo_acciones                                    10
Tasa_interes                                0.833333
Limite_credito                                     4
Porcentaje_fondo_comun                           100
Creditos_simultaneos                               3
Interes_morosidad                                0.0
Ampliacion_prestamos                               0
Interes_ampliacion                               0.0
Mod_calculo_interes                                1
Tasa_interes_prestamo_grande                     1.5
Id_socio_administrador                          1704
Id_socio_administrador_suplente                 3133
dtype: object

In [32]:
monitor_grupo.socios_acciones

,Grupo_socio_id,Socio_id,Grupo_id,Tipo_socio,Acciones,Status,CURP
0,9215,1704,2651,ADMIN,11380,1,CAAM810218MMNHLY03
1,9216,3131,2651,SOCIO,16840,1,CAAM810218MMNHLY04
2,9217,3132,2651,SOCIO,16840,1,CAAM810218MMNHLY05
3,9218,3133,2651,SUPLENTE,19850,1,RABC840919MQTMRL06
4,9219,3134,2651,SOCIO,12350,1,CAAM810218MMNHLY07
5,9220,3135,2651,SOCIO,14800,1,CAAM810218MMNHLY08
6,9221,3136,2651,SOCIO,12410,1,TOOE890722MSPRTR02
7,9222,3137,2651,SOCIO,9370,1,ROTN820917MMCJVD02
8,9223,3138,2651,SOCIO,0,1,CAAM810218MMNHLY10