In [1]:
from cosecha_colectiva import miscelaneous as m
import pandas as pd
m.try_find_conf_file()


from cosecha_colectiva import main_tester as mt
from cosecha_colectiva import config
from cosecha_colectiva import query_cosecha as qc
from cosecha_colectiva import test_cosecha_api as tca
from cosecha_colectiva import CAF_DB_Monitor as CDM

from cosecha_colectiva import miscelaneous as m

pd.set_option('display.max_columns', None)

import logging
import pathlib
from datetime import datetime, date
from dateutil.relativedelta import relativedelta

Local configuration file found !!, no need to run the configuration (unless configuration has changed)

c:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\.venv\Lib\site-packages\datajoint\plugin.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-02-09 10:50:05,806][INFO]: DataJoint 0.14.6 connected to root@junction.proxy.rlwy.net:19994

In [2]:
now = datetime.now()
log_date = now.strftime("%Y-%m-%d_%H_%M_%S")
log_file = pathlib.Path(config.log_dir, log_date+'CreacionGrupo.log')
logging.basicConfig(filename=log_file, encoding='utf-8', level=logging.INFO)

In [3]:
xls_name = 'Verde_Futuro_Test.xlsx'
xls_name = 'Verde_Futuro.xlsx'

xls_name = 'Tropa Gusgones_2.0.xlsx'
xls_name = 'Tropa Gusgones_2.0_Test.xlsx'

xls_name = 'Alcancía Viva.xlsx'
#xls_name = 'Alcancía Viva Test.xlsx'

xls_name = 'Licenciados_Asociados.xlsx'
#xls_name = 'Licenciados_Asociados_Test.xlsx'

xls_name = 'Juntas_ahorramos.xlsx'
xls_name = 'Juntes_ahorramos.xlsx'


xls_name = 'Procoseq.xlsx'

xls_name = 'CAFAM.xlsx'

xls_name = 'La Colmena.xlsx'

xls_name = 'Caja ahorro magueyeros.xlsx'

xls_name = 'Caja la llave.xlsx'

xls_name = 'Agrosemilla sin varo'
#xls_name = 'Juntos_ahorramos.xlsx'



#xls_name = 'CAF_GrupoTest.xlsx'
#xls_name = 'CAF_GrupoHidalgo.xlsx'
#xls_name = 'GrupoCafam.xlsx'

#xls_name = 'Yeiyei'

In [4]:
xls_name

'Agrosemilla sin varo'

In [5]:
[id_grupo, grupo_found] = qc.get_grupo_id_by_name(xls_name.replace(".xlsx", ""))
print(id_grupo)
print(grupo_found)
#qc.delete_grupo(id_grupo, solo_sesiones=True)
#qc.delete_grupo(id_grupo)

2639
True

In [6]:
if not grupo_found:
    grupo_data = m.read_caf_excel_sheet(pathlib.Path(xls_name), 'Grupo')
    id_grupo = qc.insert_grupo(grupo_data.to_dict('records'))
    id_grupo = id_grupo['Grupo_id']
    
id_grupo

np.int64(2639)

In [7]:
if not grupo_found:

    socios_xls = pd.DataFrame(m.get_dict_usuarios_xls(xls_name))
    # Solo crea socios cuando viene los datos completos
    if not socios_xls['Fecha_nac'].isna().all():
        print('Creando usuarios')
        tca.CAF_API_group_creation_tester.create_users(xls_name)

    grupo_socio_df = qc.prepare_insert_socio_grupo(xls_name, id_grupo)

    df_acuerdos = m.read_caf_excel_sheet(pathlib.Path(xls_name), "Acuerdos")
    df_acuerdos['Grupo_id'] = id_grupo
    df_acuerdos['Fecha_acuerdos'] = datetime.strftime(date.today(), format='%Y-%m-%d')
    df_acuerdos['Status'] = 1

    df_acuerdos['Id_socio_administrador'] = grupo_socio_df.loc[0,'Socio_id']
    df_acuerdos['Id_socio_administrador_suplente'] = grupo_socio_df.loc[1,'Socio_id']

    qc.insert_acuerdos(df_acuerdos.to_dict('records')[0])

In [8]:
qc.delete_grupo(id_grupo, solo_sesiones=True, force_delete=True, desde_sesion_0=True,conservar_acuerdos=True)


qc.restart_grupo_acciones(id_grupo, desde_sesion_0=True)

([], 'transaccion_prestamos')
([], 'transacciones')
([], 'interes_prestamo')
([], 'ganancias')
([], 'multas')
([], 'prestamos')
([], 'prestamos')
([], 'asistencias')
([], 'sesiones')
([], 'acuerdos')

In [9]:
start_month = 1
end_month = 3
initial_date = (date.today() - relativedelta(months=end_month))

monitor_grupo = CDM.CAF_DB_Monitor(id_grupo, xls_name, starting_date=initial_date)
monitor_grupo.socios_acciones

,Grupo_socio_id,Socio_id,Tipo_socio,Status,Acciones,Grupo_id,CURP,xls_order
0,9167,3100,ADMIN,1,0,2639,HELA071215MQTRNNA4,0
1,9168,3101,SOCIO,1,0,2639,GABG030718MQTRCDA6,1
2,9169,3102,SOCIO,1,0,2639,GURA070601HQTVBRA8,2
3,9170,3103,SOCIO,1,0,2639,DIRO050321HQTZSSA2,3
4,9171,3105,SUPLENTE,1,0,2639,MAZK070210MQTRXRA0,4
5,9172,3104,SOCIO,1,0,2639,PEMA061115HQTRTNA2,5
6,9224,3139,SOCIO,1,0,2639,PEVG050424HQTRNLA7,6
7,9225,2950,SOCIO,1,0,2639,LUSE860715HDFNND00,7

In [10]:

for month in range(start_month, end_month+1):

    print('month: ', month)

    try:
        monitor_grupo.actualiza_todo_sesion(xls_name, month, type_xls='NEW', bd_update=True, unique_session_to_update=False)
    except Exception as e:
        print(e)
        raise(e)
        break

month:  1
ganancias_totales_sesion
0
ganancias_totales_floor
0.0
sob_acciones
0.0
month:  2
ganancias_totales_sesion
0
ganancias_totales_floor
0.0
sob_acciones
0.0
month:  3
ganancias_totales_sesion
0
ganancias_totales_floor
0.0
sob_acciones
0.0

In [11]:
monitor_grupo.socios_acciones

,Grupo_socio_id,Socio_id,Grupo_id,Tipo_socio,Acciones,Status,CURP
0,9167,3100,2639,ADMIN,350,1,HELA071215MQTRNNA4
1,9168,3101,2639,SOCIO,400,1,GABG030718MQTRCDA6
2,9169,3102,2639,SOCIO,200,1,GURA070601HQTVBRA8
3,9170,3103,2639,SOCIO,350,1,DIRO050321HQTZSSA2
4,9171,3105,2639,SUPLENTE,400,1,MAZK070210MQTRXRA0
5,9172,3104,2639,SOCIO,300,1,PEMA061115HQTRTNA2
6,9224,3139,2639,SOCIO,100,1,PEVG050424HQTRNLA7
7,9225,2950,2639,SOCIO,0,1,LUSE860715HDFNND00

In [12]:
monitor_grupo.prestamos

Empty DataFrame
Columns: [Prestamo_id, Monto_prestamo, Monto_pagado, Interes_generado, Interes_pagado, Fecha_inicial, Fecha_final, Estatus_ampliacion, Observaciones, Num_sesiones, Sesiones_restantes, Estatus_prestamo, Socio_id, Sesion_id, Acuerdos_id, Prestamo_original_id, Grupo_id, Tasa_interes, Limite_credito, Creditos_simultaneos, Interes_morosidad, Ampliacion_prestamos, Interes_ampliacion, Mod_calculo_interes, Tasa_interes_prestamo_grande, interes_futuro, Ultimo_interes_pagado, debe_interes, sobrante_abono, Ultimo_abono, Status_socio]
Index: []

In [13]:
monitor_grupo.sesiones_bd

,Sesion_id,Fecha,Activa,Caja,Acciones,Ganancias,Fecha_prox_reunion,Lugar_prox_reunion,Tipo_sesion,Grupo_id,created_at
0,20016,2025-11-09,0,1200,1200,0.0,2025-12-09,Sesion creada en script,1,2639,2025-11-09
1,20017,2025-12-09,0,1800,1800,0.0,2026-01-09,Sesion creada en script,1,2639,2025-12-09
2,20018,2026-01-09,0,2100,2100,0.0,2026-02-09,Sesion creada en script,1,2639,2026-01-09

In [14]:
monitor_grupo.caja

np.float64(1720.0)

In [14]:
monitor_grupo.ganancias

,Ganancias_id,Ganancia_accion,Monto_ganancia,Entregada,Socio_id,Sesion_id,periodo
0,81125,0.0,0.0,0,3100,20016,nuevo
1,81126,0.0,0.0,0,3101,20016,nuevo
2,81127,0.0,0.0,0,3102,20016,nuevo
3,81128,0.0,0.0,0,3103,20016,nuevo
4,81129,0.0,0.0,0,3105,20016,nuevo
5,81130,0.0,0.0,0,3104,20016,nuevo
6,81131,0.0,0.0,0,3139,20017,nuevo
7,81132,0.0,0.0,0,3102,20017,nuevo
8,81133,0.0,0.0,0,3101,20017,nuevo
9,81134,0.0,0.0,0,3100,20017,nuevo
10,81135,0.0,0.0,0,3103,20017,nuevo
11,81136,0.0,0.0,0,3105,20017,nuevo
12,81137,0.0,0.0,0,3104,20017,nuevo
13,81138,0.0,0.0,0,3139,20018,nuevo
14,81139,0.0,0.0,0,3102,20018,nuevo
15,81140,0.0,0.0,0,3104,20018,nuevo
16,81141,0.0,0.0,0,3100,20018,nuevo
17,81142,0.0,0.0,0,3103,20018,nuevo
18,81143,0.0,0.0,0,3101,20018,nuevo
19,81144,0.0,0.0,0,3105,20018,nuevo

In [15]:
monitor_grupo.multas

Empty DataFrame
Columns: [Multa_id, Monto_multa, Descripcion, Status, Sesion_id, Socio_id, Transaccion_id, created_at, Pago_en_sesion]
Index: []

In [16]:
monitor_grupo.acuerdos

Acuerdo_id                                      2272
Id_temporal_admin                               None
id_treasurer_user                               None
id_secretary_user                               None
allow_action_retreat_on_normal_session             0
Grupo_id                                        2639
Fecha_acuerdos                            2025-10-24
Fecha_acuerdos_fin                        2026-10-24
Status                                             1
Periodo_reuniones                                  4
Periodo_cargos                                     4
Limite_inasistencias                               3
Minimo_aportacion                                200
Costo_acciones                                    10
Tasa_interes                                     1.0
Limite_credito                                     4
Porcentaje_fondo_comun                           100
Creditos_simultaneos                               1
Interes_morosidad                                3.5
Ampliacion_prestamos                               1
Interes_ampliacion                               1.0
Mod_calculo_interes                                1
Tasa_interes_prestamo_grande                     1.5
Id_socio_administrador                          3100
Id_socio_administrador_suplente                 3105
dtype: object

In [17]:
monitor_grupo.ganancias_acum.sum()

Monto_ganancia    0.0
dtype: float64

In [18]:
monitor_grupo.multas

Empty DataFrame
Columns: [Multa_id, Monto_multa, Descripcion, Status, Sesion_id, Socio_id, Transaccion_id, created_at, Pago_en_sesion]
Index: []

In [19]:
monitor_grupo.transacciones_prestamo_bd

Empty DataFrame
Columns: [Transaccion_prestamo_id, Prestamo_id, Transaccion_id, Monto_abono_prestamo, Monto_abono_interes]
Index: []

In [20]:
monitor_grupo.transacciones_bd

,Transaccion_id,Cantidad_movimiento,Caja,Timestamp,Sesion_id,Socio_id,Acuerdo_id,Catalogo_id
0,41064,200,200,2025-11-09 00:00:00,20016,3100,2272,COMPRA_ACCION
1,41065,200,400,2025-11-09 00:00:00,20016,3101,2272,COMPRA_ACCION
2,41066,200,600,2025-11-09 00:00:00,20016,3102,2272,COMPRA_ACCION
3,41067,200,800,2025-11-09 00:00:00,20016,3103,2272,COMPRA_ACCION
4,41068,200,1000,2025-11-09 00:00:00,20016,3105,2272,COMPRA_ACCION
5,41069,200,1200,2025-11-09 00:00:00,20016,3104,2272,COMPRA_ACCION
6,41070,100,1300,2025-12-09 00:00:00,20017,3100,2272,COMPRA_ACCION
7,41071,100,1400,2025-12-09 00:00:00,20017,3101,2272,COMPRA_ACCION
8,41072,100,1500,2025-12-09 00:00:00,20017,3103,2272,COMPRA_ACCION
9,41073,100,1600,2025-12-09 00:00:00,20017,3105,2272,COMPRA_ACCION
10,41074,100,1700,2025-12-09 00:00:00,20017,3104,2272,COMPRA_ACCION
11,41075,100,1800,2025-12-09 00:00:00,20017,3139,2272,COMPRA_ACCION
12,41076,50,1850,2026-01-09 00:00:00,20018,3100,2272,COMPRA_ACCION
13,41077,100,1950,2026-01-09 00:00:00,20018,3101,2272,COMPRA_ACCION
14,41078,50,2000,2026-01-09 00:00:00,20018,3103,2272,COMPRA_ACCION
15,41079,100,2100,2026-01-09 00:00:00,20018,3105,2272,COMPRA_ACCION