In [1]:
from cosecha_colectiva import miscelaneous as m
import pandas as pd
m.try_find_conf_file()


from cosecha_colectiva import main_tester as mt
from cosecha_colectiva import config
from cosecha_colectiva import query_cosecha as qc
from cosecha_colectiva import test_cosecha_api as tca
from cosecha_colectiva import CAF_DB_Monitor as CDM

from cosecha_colectiva import miscelaneous as m

pd.set_option('display.max_columns', None)

import logging
import pathlib
from datetime import datetime, date
from dateutil.relativedelta import relativedelta

Local configuration file found !!, no need to run the configuration (unless configuration has changed)

c:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\.venv\Lib\site-packages\datajoint\plugin.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-02-04 17:32:54,847][INFO]: DataJoint 0.14.6 connected to root@junction.proxy.rlwy.net:19994

In [2]:
now = datetime.now()
log_date = now.strftime("%Y-%m-%d_%H_%M_%S")
log_file = pathlib.Path(config.log_dir, log_date+'CreacionGrupo.log')
logging.basicConfig(filename=log_file, encoding='utf-8', level=logging.INFO)

In [3]:
xls_name = 'Verde_Futuro_Test.xlsx'
xls_name = 'Verde_Futuro.xlsx'

xls_name = 'Tropa Gusgones_2.0.xlsx'
xls_name = 'Tropa Gusgones_2.0_Test.xlsx'

xls_name = 'Alcancía Viva.xlsx'
#xls_name = 'Alcancía Viva Test.xlsx'

xls_name = 'Licenciados_Asociados.xlsx'
#xls_name = 'Licenciados_Asociados_Test.xlsx'

xls_name = 'Juntas_ahorramos.xlsx'
xls_name = 'Juntes_ahorramos.xlsx'


xls_name = 'Procoseq.xlsx'

xls_name = 'CAFAM.xlsx'

xls_name = 'La Colmena.xlsx'

xls_name = 'Caja ahorro magueyeros.xlsx'

xls_name = 'Caja la llave.xlsx'
#xls_name = 'Juntos_ahorramos.xlsx'



#xls_name = 'CAF_GrupoTest.xlsx'
#xls_name = 'CAF_GrupoHidalgo.xlsx'
#xls_name = 'GrupoCafam.xlsx'

#xls_name = 'Yeiyei'

In [4]:
xls_name

'Caja la llave.xlsx'

In [5]:
[id_grupo, grupo_found] = qc.get_grupo_id_by_name(xls_name.replace(".xlsx", ""))
print(id_grupo)
print(grupo_found)
#qc.delete_grupo(id_grupo, solo_sesiones=True)
#qc.delete_grupo(id_grupo)

2641
True

In [6]:
if not grupo_found:
    grupo_data = m.read_caf_excel_sheet(pathlib.Path(xls_name), 'Grupo')
    id_grupo = qc.insert_grupo(grupo_data.to_dict('records'))
    id_grupo = id_grupo['Grupo_id']
    
id_grupo

np.int64(2641)

In [7]:
if not grupo_found:

    socios_xls = pd.DataFrame(m.get_dict_usuarios_xls(xls_name))
    # Solo crea socios cuando viene los datos completos
    if not socios_xls['Fecha_nac'].isna().all():
        print('Creando usuarios')
        tca.CAF_API_group_creation_tester.create_users(xls_name)

    grupo_socio_df = qc.prepare_insert_socio_grupo(xls_name, id_grupo)

    df_acuerdos = m.read_caf_excel_sheet(pathlib.Path(xls_name), "Acuerdos")
    df_acuerdos['Grupo_id'] = id_grupo
    df_acuerdos['Fecha_acuerdos'] = datetime.strftime(date.today(), format='%Y-%m-%d')
    df_acuerdos['Status'] = 1

    df_acuerdos['Id_socio_administrador'] = grupo_socio_df.loc[0,'Socio_id']
    df_acuerdos['Id_socio_administrador_suplente'] = grupo_socio_df.loc[1,'Socio_id']

    qc.insert_acuerdos(df_acuerdos.to_dict('records')[0])

In [8]:
qc.delete_grupo(id_grupo, solo_sesiones=True, force_delete=True, desde_sesion_0=True,conservar_acuerdos=True)


qc.restart_grupo_acciones(id_grupo, desde_sesion_0=True)

([{'Transaccion_prestamo_id': np.int64(11247)}], 'transaccion_prestamos')
DELETE from railway.transaccion_prestamos WHERE Transaccion_prestamo_id in (11247)
([{'Transaccion_id': np.int64(40978)}, {'Transaccion_id': np.int64(40979)}, {'Transaccion_id': np.int64(40980)}, {'Transaccion_id': np.int64(40981)}, {'Transaccion_id': np.int64(40982)}, {'Transaccion_id': np.int64(40983)}, {'Transaccion_id': np.int64(40984)}, {'Transaccion_id': np.int64(40985)}, {'Transaccion_id': np.int64(40986)}, {'Transaccion_id': np.int64(40987)}, {'Transaccion_id': np.int64(40988)}, {'Transaccion_id': np.int64(40989)}, {'Transaccion_id': np.int64(40990)}, {'Transaccion_id': np.int64(40991)}, {'Transaccion_id': np.int64(40992)}, {'Transaccion_id': np.int64(40993)}, {'Transaccion_id': np.int64(40994)}, {'Transaccion_id': np.int64(40995)}, {'Transaccion_id': np.int64(40996)}, {'Transaccion_id': np.int64(40997)}, {'Transaccion_id': np.int64(40998)}, {'Transaccion_id': np.int64(40999)}, {'Transaccion_id': np.int64(41000)}, {'Transaccion_id': np.int64(41001)}, {'Transaccion_id': np.int64(41002)}, {'Transaccion_id': np.int64(41003)}, {'Transaccion_id': np.int64(41004)}, {'Transaccion_id': np.int64(41005)}, {'Transaccion_id': np.int64(41006)}, {'Transaccion_id': np.int64(41007)}, {'Transaccion_id': np.int64(41008)}, {'Transaccion_id': np.int64(41009)}, {'Transaccion_id': np.int64(41010)}, {'Transaccion_id': np.int64(41011)}, {'Transaccion_id': np.int64(41012)}, {'Transaccion_id': np.int64(41013)}, {'Transaccion_id': np.int64(41014)}, {'Transaccion_id': np.int64(41015)}, {'Transaccion_id': np.int64(41016)}, {'Transaccion_id': np.int64(41017)}, {'Transaccion_id': np.int64(41018)}, {'Transaccion_id': np.int64(41019)}, {'Transaccion_id': np.int64(41020)}], 'transacciones')
DELETE from railway.transacciones WHERE Transaccion_id in (40978, 40979, 40980, 40981, 40982, 40983, 40984, 40985, 40986, 40987, 40988, 40989, 40990, 40991, 40992, 40993, 40994, 40995, 40996, 40997, 40998, 40999, 41000, 41001, 41002, 41003, 41004, 41005, 41006, 41007, 41008, 41009, 41010, 41011, 41012, 41013, 41014, 41015, 41016, 41017, 41018, 41019, 41020)
([{'Interes_prestamo_id': np.int64(104212)}], 'interes_prestamo')
DELETE from railway.interes_prestamo WHERE Interes_prestamo_id in (104212)
([{'Ganancias_id': np.int64(81053)}, {'Ganancias_id': np.int64(81054)}, {'Ganancias_id': np.int64(81055)}, {'Ganancias_id': np.int64(81056)}, {'Ganancias_id': np.int64(81057)}, {'Ganancias_id': np.int64(81058)}, {'Ganancias_id': np.int64(81059)}, {'Ganancias_id': np.int64(81060)}, {'Ganancias_id': np.int64(81061)}, {'Ganancias_id': np.int64(81062)}, {'Ganancias_id': np.int64(81063)}, {'Ganancias_id': np.int64(81064)}, {'Ganancias_id': np.int64(81065)}, {'Ganancias_id': np.int64(81066)}, {'Ganancias_id': np.int64(81067)}, {'Ganancias_id': np.int64(81068)}, {'Ganancias_id': np.int64(81069)}, {'Ganancias_id': np.int64(81070)}, {'Ganancias_id': np.int64(81071)}, {'Ganancias_id': np.int64(81072)}, {'Ganancias_id': np.int64(81073)}, {'Ganancias_id': np.int64(81074)}, {'Ganancias_id': np.int64(81075)}, {'Ganancias_id': np.int64(81076)}, {'Ganancias_id': np.int64(81077)}, {'Ganancias_id': np.int64(81078)}, {'Ganancias_id': np.int64(81079)}, {'Ganancias_id': np.int64(81080)}, {'Ganancias_id': np.int64(81081)}, {'Ganancias_id': np.int64(81082)}, {'Ganancias_id': np.int64(81083)}, {'Ganancias_id': np.int64(81084)}, {'Ganancias_id': np.int64(81085)}, {'Ganancias_id': np.int64(81086)}, {'Ganancias_id': np.int64(81087)}, {'Ganancias_id': np.int64(81088)}], 'ganancias')
DELETE from railway.ganancias WHERE Ganancias_id in (81053, 81054, 81055, 81056, 81057, 81058, 81059, 81060, 81061, 81062, 81063, 81064, 81065, 81066, 81067, 81068, 81069, 81070, 81071, 81072, 81073, 81074, 81075, 81076, 81077, 81078, 81079, 81080, 81081, 81082, 81083, 81084, 81085, 81086, 81087, 81088)
([{'Multa_id': np.int64(3678)}, {'Multa_id': np.int64(3679)}, {'Multa_id': np.int64(3680)}, {'Multa_id': np.int64(3681)}], 'multas')
DELETE from railway.multas WHERE Multa_id in (3678, 3679, 3680, 3681)
([], 'prestamos')
([{'Prestamo_id': np.int64(6843)}, {'Prestamo_id': np.int64(6844)}], 'prestamos')
DELETE from railway.prestamos WHERE Prestamo_id in (6843, 6844)
([{'Asistencia_id': np.int64(139605)}, {'Asistencia_id': np.int64(139606)}, {'Asistencia_id': np.int64(139607)}, {'Asistencia_id': np.int64(139608)}, {'Asistencia_id': np.int64(139609)}, {'Asistencia_id': np.int64(139610)}, {'Asistencia_id': np.int64(139611)}, {'Asistencia_id': np.int64(139612)}, {'Asistencia_id': np.int64(139613)}, {'Asistencia_id': np.int64(139614)}, {'Asistencia_id': np.int64(139615)}, {'Asistencia_id': np.int64(139616)}, {'Asistencia_id': np.int64(139617)}, {'Asistencia_id': np.int64(139618)}, {'Asistencia_id': np.int64(139619)}, {'Asistencia_id': np.int64(139620)}, {'Asistencia_id': np.int64(139621)}, {'Asistencia_id': np.int64(139622)}, {'Asistencia_id': np.int64(139623)}, {'Asistencia_id': np.int64(139624)}, {'Asistencia_id': np.int64(139625)}, {'Asistencia_id': np.int64(139626)}, {'Asistencia_id': np.int64(139627)}, {'Asistencia_id': np.int64(139628)}, {'Asistencia_id': np.int64(139629)}, {'Asistencia_id': np.int64(139630)}, {'Asistencia_id': np.int64(139631)}, {'Asistencia_id': np.int64(139632)}, {'Asistencia_id': np.int64(139633)}, {'Asistencia_id': np.int64(139634)}, {'Asistencia_id': np.int64(139635)}, {'Asistencia_id': np.int64(139636)}, {'Asistencia_id': np.int64(139637)}, {'Asistencia_id': np.int64(139638)}, {'Asistencia_id': np.int64(139639)}, {'Asistencia_id': np.int64(139640)}], 'asistencias')
DELETE from railway.asistencias WHERE Asistencia_id in (139605, 139606, 139607, 139608, 139609, 139610, 139611, 139612, 139613, 139614, 139615, 139616, 139617, 139618, 139619, 139620, 139621, 139622, 139623, 139624, 139625, 139626, 139627, 139628, 139629, 139630, 139631, 139632, 139633, 139634, 139635, 139636, 139637, 139638, 139639, 139640)
([{'Sesion_id': np.int64(20009)}, {'Sesion_id': np.int64(20010)}, {'Sesion_id': np.int64(20011)}], 'sesiones')
DELETE from railway.sesiones WHERE Sesion_id in (20009, 20010, 20011)
([], 'acuerdos')

In [9]:
start_month = 1
end_month = 3
initial_date = (date.today() - relativedelta(months=end_month))

monitor_grupo = CDM.CAF_DB_Monitor(id_grupo, xls_name, starting_date=initial_date)
monitor_grupo.socios_acciones

,Grupo_socio_id,Socio_id,Tipo_socio,Status,Acciones,Grupo_id,CURP,xls_order
0,9174,3106,SOCIO,1,0,2641,GAHA771128HQTRRD00,0
1,9175,3140,ADMIN,1,0,2641,EIVB800812MDFNZT01,1
2,9176,3108,SOCIO,1,0,2641,HECD711022MQTRRL16,2
3,9177,3109,SOCIO,1,0,2641,CAGL610902MQTRNS05,3
4,9178,3110,SUPLENTE,1,0,2641,AACT750923MQTLRR03,4
5,9179,3111,SOCIO,1,0,2641,HEAL010827MQTRLZA0,5
6,9180,3115,SOCIO,1,0,2641,HECM730507HQTRRN03,6
7,9181,3116,SOCIO,1,0,2641,GAEL130825HQTRNSA3,7
8,9182,3118,SOCIO,1,0,2641,HEAJ071207HQTRLSA7,8
9,9183,3119,SOCIO,1,0,2641,GAEF151019HQTRNRA0,9
10,9184,3112,SOCIO,1,0,2641,GAEE020714HQTRNRA8,10
11,9185,3117,SOCIO,1,0,2641,GAEE120327HQTRNMA9,11

In [10]:

for month in range(start_month, end_month+1):

    print('month: ', month)

    try:
        monitor_grupo.actualiza_todo_sesion(xls_name, month, type_xls='NEW', bd_update=True, unique_session_to_update=False)
    except Exception as e:
        print(e)
        raise(e)
        break

month:  1
ganancias_totales_sesion
0
ganancias_totales_floor
0.0
sob_acciones
0.0
ganancias_sesion
    Acciones  Socio_id  Monto_ganancia_floor  sobrante_Monto_ganancia  \
0        200      3106                   0.0                      0.0
1        200      3140                   0.0                      0.0
2        200      3108                   0.0                      0.0
3        200      3109                   0.0                      0.0
4        200      3110                   0.0                      0.0
5        200      3111                   0.0                      0.0
6        200      3115                   0.0                      0.0
7        200      3116                   0.0                      0.0
8        200      3118                   0.0                      0.0
9        200      3119                   0.0                      0.0
10       200      3112                   0.0                      0.0
11       200      3117                   0.0                      0.0

    Monto_ganancia  Entregada  Sesion_id  Ganancias_id  Ganancia_accion  \
0              0.0          0      20012         -1000              0.0
1              0.0          0      20012          -999              0.0
2              0.0          0      20012          -998              0.0
3              0.0          0      20012          -997              0.0
4              0.0          0      20012          -996              0.0
5              0.0          0      20012          -995              0.0
6              0.0          0      20012          -994              0.0
7              0.0          0      20012          -993              0.0
8              0.0          0      20012          -992              0.0
9              0.0          0      20012          -991              0.0
10             0.0          0      20012          -990              0.0
11             0.0          0      20012          -989              0.0

   periodo
0    nuevo
1    nuevo
2    nuevo
3    nuevo
4    nuevo
5    nuevo
6    nuevo
7    nuevo
8    nuevo
9    nuevo
10   nuevo
11   nuevo
month:  2
ganancias_totales_sesion
0
ganancias_totales_floor
0.0
sob_acciones
0.0
ganancias_sesion
    Acciones  Socio_id  Monto_ganancia_floor  sobrante_Monto_ganancia  \
0        400      3109                   0.0                      0.0
1        400      3116                   0.0                      0.0
2        400      3115                   0.0                      0.0
3        400      3118                   0.0                      0.0
4        400      3119                   0.0                      0.0
5        400      3117                   0.0                      0.0
6        450      3111                   0.0                      0.0
7        500      3110                   0.0                      0.0
8        500      3112                   0.0                      0.0
9        700      3106                   0.0                      0.0
10      1200      3140                   0.0                      0.0
11      2100      3108                   0.0                      0.0

    Monto_ganancia  Entregada  Sesion_id  Ganancias_id  Ganancia_accion  \
0              0.0          0      20013         -1000              0.0
1              0.0          0      20013          -999              0.0
2              0.0          0      20013          -998              0.0
3              0.0          0      20013          -997              0.0
4              0.0          0      20013          -996              0.0
5              0.0          0      20013          -995              0.0
6              0.0          0      20013          -994              0.0
7              0.0          0      20013          -993              0.0
8              0.0          0      20013          -992              0.0
9              0.0          0      20013          -991              0.0
10             0.0          0      20013          -990              0.0
11             0.0          0      20013          -989              0.0

   periodo
0    nuevo
1    nuevo
2    nuevo
3    nuevo
4    nuevo
5    nuevo
6    nuevo
7    nuevo
8    nuevo
9    nuevo
10   nuevo
11   nuevo
month:  3

C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:290: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[15.0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  prestamos_activos.loc[prestamos_activos['sobrante_abono'] >= 0, 'Ultimo_interes_pagado'] =\
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[15.0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.prestamos.loc[prestamos_activos.index] = prestamos_activos
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:167: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  prestamos_socios = prestamos_socios.fillna(0)
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:336: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  multas_activas['PAGO_MULTA'] = multas_activas['PAGO_MULTA'].fillna(0)

ganancias_totales_sesion
95.0
ganancias_totales_floor
93.0
sob_acciones
4.0
ganancias_sesion
    Acciones  Socio_id  Monto_ganancia_floor  sobrante_Monto_ganancia  \
0        600      3116                   4.5                      0.5
1        600      3118                   4.5                      0.5
2        600      3117                   4.5                      0.5
3        700      3119                   5.0                      0.5
4        750      3112                   5.5                      0.0
5        750      3111                   5.5                      0.0
6        800      3115                   6.0                      0.0
7        800      3110                   6.0                      0.0
8        900      3109                   6.5                      0.0
9       1200      3106                   9.0                      0.0
10      1700      3140                  12.5                      0.0
11      3100      3108                  23.5                      0.0

    Monto_ganancia  Entregada  Sesion_id  Ganancias_id  Ganancia_accion  \
0              5.0          0      20014         -1000           0.0076
1              5.0          0      20014          -999           0.0076
2              5.0          0      20014          -998           0.0076
3              5.5          0      20014          -997           0.0076
4              5.5          0      20014          -996           0.0076
5              5.5          0      20014          -995           0.0076
6              6.0          0      20014          -994           0.0076
7              6.0          0      20014          -993           0.0076
8              6.5          0      20014          -992           0.0076
9              9.0          0      20014          -991           0.0076
10            12.5          0      20014          -990           0.0076
11            23.5          0      20014          -989           0.0076

   periodo
0    nuevo
1    nuevo
2    nuevo
3    nuevo
4    nuevo
5    nuevo
6    nuevo
7    nuevo
8    nuevo
9    nuevo
10   nuevo
11   nuevo

In [11]:
monitor_grupo.socios_acciones

,Grupo_socio_id,Socio_id,Grupo_id,Tipo_socio,Acciones,Status,CURP
0,9174,3106,2641,SOCIO,1200,1,GAHA771128HQTRRD00
1,9175,3140,2641,ADMIN,1700,1,EIVB800812MDFNZT01
2,9176,3108,2641,SOCIO,3100,1,HECD711022MQTRRL16
3,9177,3109,2641,SOCIO,900,1,CAGL610902MQTRNS05
4,9178,3110,2641,SUPLENTE,800,1,AACT750923MQTLRR03
5,9179,3111,2641,SOCIO,750,1,HEAL010827MQTRLZA0
6,9180,3115,2641,SOCIO,800,1,HECM730507HQTRRN03
7,9181,3116,2641,SOCIO,600,1,GAEL130825HQTRNSA3
8,9182,3118,2641,SOCIO,600,1,HEAJ071207HQTRLSA7
9,9183,3119,2641,SOCIO,700,1,GAEF151019HQTRNRA0
10,9184,3112,2641,SOCIO,750,1,GAEE020714HQTRNRA8
11,9185,3117,2641,SOCIO,600,1,GAEE120327HQTRNMA9

In [12]:
monitor_grupo.prestamos

,Prestamo_id,Monto_prestamo,Monto_pagado,Interes_generado,Interes_pagado,Fecha_inicial,Fecha_final,Estatus_ampliacion,Observaciones,Num_sesiones,Sesiones_restantes,Estatus_prestamo,Socio_id,Sesion_id,Acuerdos_id,Prestamo_original_id,Grupo_id,Tasa_interes,Limite_credito,Creditos_simultaneos,Interes_morosidad,Ampliacion_prestamos,Interes_ampliacion,Mod_calculo_interes,Tasa_interes_prestamo_grande,interes_futuro,Ultimo_interes_pagado,debe_interes,sobrante_abono,Ultimo_abono,Status_socio
0,6845,1000.0,125.0,15.0,15.0,2025-12-04,2026-10-04,False,Préstamo generado en script automático,10,9,0,3116,20013,2273,None,2641,1.5,10,3,1.5,1,0.0,1,None,15.0,15.0,15.0,125.0,140.0,1
1,6846,10000.0,0,0,0,2026-01-04,2026-04-04,False,Préstamo generado en script automático,3,3,0,3106,20014,2273,None,2641,1.5,10,3,1.5,1,0.0,1,None,150.0,0,0,0,0,1

In [13]:
monitor_grupo.sesiones_bd

,Sesion_id,Fecha,Activa,Caja,Acciones,Ganancias,Fecha_prox_reunion,Lugar_prox_reunion,Tipo_sesion,Grupo_id,created_at
0,20012,2025-11-04,0,2400,2400,0.0,2025-12-04,Sesion creada en script,1,2641,2025-11-04
1,20013,2025-12-04,0,6850.0,7850,0.0,2026-01-04,Sesion creada en script,1,2641,2025-12-04
2,20014,2026-01-04,0,1720.0,12500,95.0,2026-02-04,Sesion creada en script,1,2641,2026-01-04

In [14]:
monitor_grupo.caja

np.float64(1720.0)

In [15]:
monitor_grupo.ganancias

,Ganancias_id,Ganancia_accion,Monto_ganancia,Entregada,Socio_id,Sesion_id,periodo
0,81089,0.0000,0.0,0,3106,20012,nuevo
1,81090,0.0000,0.0,0,3140,20012,nuevo
2,81091,0.0000,0.0,0,3108,20012,nuevo
3,81092,0.0000,0.0,0,3109,20012,nuevo
4,81093,0.0000,0.0,0,3110,20012,nuevo
5,81094,0.0000,0.0,0,3111,20012,nuevo
6,81095,0.0000,0.0,0,3115,20012,nuevo
7,81096,0.0000,0.0,0,3116,20012,nuevo
8,81097,0.0000,0.0,0,3118,20012,nuevo
9,81098,0.0000,0.0,0,3119,20012,nuevo
10,81099,0.0000,0.0,0,3112,20012,nuevo
11,81100,0.0000,0.0,0,3117,20012,nuevo
12,81101,0.0000,0.0,0,3109,20013,nuevo
13,81102,0.0000,0.0,0,3116,20013,nuevo
14,81103,0.0000,0.0,0,3115,20013,nuevo
15,81104,0.0000,0.0,0,3118,20013,nuevo
16,81105,0.0000,0.0,0,3119,20013,nuevo
17,81106,0.0000,0.0,0,3117,20013,nuevo
18,81107,0.0000,0.0,0,3111,20013,nuevo
19,81108,0.0000,0.0,0,3110,20013,nuevo
20,81109,0.0000,0.0,0,3112,20013,nuevo
21,81110,0.0000,0.0,0,3106,20013,nuevo
22,81111,0.0000,0.0,0,3140,20013,nuevo
23,81112,0.0000,0.0,0,3108,20013,nuevo
24,81113,0.0076,5.0,0,3116,20014,nuevo
25,81114,0.0076,5.0,0,3118,20014,nuevo
26,81115,0.0076,5.0,0,3117,20014,nuevo
27,81116,0.0076,5.5,0,3119,20014,nuevo
28,81117,0.0076,5.5,0,3112,20014,nuevo
29,81118,0.0076,5.5,0,3111,20014,nuevo
30,81119,0.0076,6.0,0,3115,20014,nuevo
31,81120,0.0076,6.0,0,3110,20014,nuevo
32,81121,0.0076,6.5,0,3109,20014,nuevo
33,81122,0.0076,9.0,0,3106,20014,nuevo
34,81123,0.0076,12.5,0,3140,20014,nuevo
35,81124,0.0076,23.5,0,3108,20014,nuevo

In [16]:
monitor_grupo.multas

,Multa_id,Monto_multa,Descripcion,Status,Sesion_id,Socio_id,Transaccion_id,created_at,Pago_en_sesion
0,3682,20.0,Multa # 1 socio 3110 grupo: 2641 con script,1,20014,3110,None,2026-01-04 00:00:00,1
1,3683,20.0,Multa # 1 socio 3111 grupo: 2641 con script,1,20014,3111,None,2026-01-04 00:00:00,1
2,3684,20.0,Multa # 1 socio 3115 grupo: 2641 con script,1,20014,3115,None,2026-01-04 00:00:00,1
3,3685,20.0,Multa # 1 socio 3118 grupo: 2641 con script,1,20014,3118,None,2026-01-04 00:00:00,1

In [17]:
monitor_grupo.acuerdos

Acuerdo_id                                      2273
Id_temporal_admin                               None
id_treasurer_user                               None
id_secretary_user                               None
allow_action_retreat_on_normal_session             0
Grupo_id                                        2641
Fecha_acuerdos                            2025-11-22
Fecha_acuerdos_fin                        2026-05-22
Status                                             1
Periodo_reuniones                                  3
Periodo_cargos                                     2
Limite_inasistencias                               3
Minimo_aportacion                                200
Costo_acciones                                    10
Tasa_interes                                     1.5
Limite_credito                                    10
Porcentaje_fondo_comun                          None
Creditos_simultaneos                               3
Interes_morosidad                                1.5
Ampliacion_prestamos                               1
Interes_ampliacion                               0.0
Mod_calculo_interes                                1
Tasa_interes_prestamo_grande                    None
Id_socio_administrador                          3107
Id_socio_administrador_suplente                 3110
dtype: object

In [18]:
monitor_grupo.ganancias_acum.sum()

Monto_ganancia    95.0
dtype: float64

In [19]:
monitor_grupo.multas

,Multa_id,Monto_multa,Descripcion,Status,Sesion_id,Socio_id,Transaccion_id,created_at,Pago_en_sesion
0,3682,20.0,Multa # 1 socio 3110 grupo: 2641 con script,1,20014,3110,None,2026-01-04 00:00:00,1
1,3683,20.0,Multa # 1 socio 3111 grupo: 2641 con script,1,20014,3111,None,2026-01-04 00:00:00,1
2,3684,20.0,Multa # 1 socio 3115 grupo: 2641 con script,1,20014,3115,None,2026-01-04 00:00:00,1
3,3685,20.0,Multa # 1 socio 3118 grupo: 2641 con script,1,20014,3118,None,2026-01-04 00:00:00,1

In [21]:
monitor_grupo.transacciones_prestamo_bd

,index,Transaccion_prestamo_id,Prestamo_id,Transaccion_id,Monto_abono_prestamo,Monto_abono_interes
0,0,11248,6845,41058,125.0,15.0

In [23]:
monitor_grupo.transacciones_bd

,Transaccion_id,Cantidad_movimiento,Caja,Timestamp,Sesion_id,Socio_id,Acuerdo_id,Catalogo_id,Prestamo_id,Ultimo_interes_pagado,sobrante_abono,Multa_id
0,41021,200,200,2025-11-04 00:00:00,20012,3106,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
1,41022,200,400,2025-11-04 00:00:00,20012,3140,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
2,41023,200,600,2025-11-04 00:00:00,20012,3108,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
3,41024,200,800,2025-11-04 00:00:00,20012,3109,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
4,41025,200,1000,2025-11-04 00:00:00,20012,3110,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
5,41026,200,1200,2025-11-04 00:00:00,20012,3111,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
6,41027,200,1400,2025-11-04 00:00:00,20012,3115,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
7,41028,200,1600,2025-11-04 00:00:00,20012,3116,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
8,41029,200,1800,2025-11-04 00:00:00,20012,3118,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
9,41030,200,2000,2025-11-04 00:00:00,20012,3119,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
10,41031,200,2200,2025-11-04 00:00:00,20012,3112,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
11,41032,200,2400,2025-11-04 00:00:00,20012,3117,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
12,41033,500,2900,2025-12-04 00:00:00,20013,3106,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
13,41034,1000,3900,2025-12-04 00:00:00,20013,3140,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
14,41035,1900,5800,2025-12-04 00:00:00,20013,3108,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
15,41036,200,6000,2025-12-04 00:00:00,20013,3109,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
16,41037,300,6300,2025-12-04 00:00:00,20013,3110,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
17,41038,250,6550,2025-12-04 00:00:00,20013,3111,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
18,41039,200,6750,2025-12-04 00:00:00,20013,3115,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
19,41040,200,6950,2025-12-04 00:00:00,20013,3116,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
20,41041,200,7150,2025-12-04 00:00:00,20013,3118,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
21,41042,200,7350,2025-12-04 00:00:00,20013,3119,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
22,41043,300,7650,2025-12-04 00:00:00,20013,3112,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
23,41044,200,7850,2025-12-04 00:00:00,20013,3117,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
24,41045,-1000.0,6850.0,2025-12-04 00:00:00,20013,3116,2273,ENTREGA_PRESTAMO,6845,NaN,NaN,NaN
25,41046,500,7350.0,2026-01-04 00:00:00,20014,3106,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
26,41047,500,7850.0,2026-01-04 00:00:00,20014,3140,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
27,41048,1000,8850.0,2026-01-04 00:00:00,20014,3108,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
28,41049,500,9350.0,2026-01-04 00:00:00,20014,3109,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
29,41050,300,9650.0,2026-01-04 00:00:00,20014,3110,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
30,41051,300,9950.0,2026-01-04 00:00:00,20014,3111,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
31,41052,400,10350.0,2026-01-04 00:00:00,20014,3115,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
32,41053,200,10550.0,2026-01-04 00:00:00,20014,3116,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
33,41054,200,10750.0,2026-01-04 00:00:00,20014,3118,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
34,41055,300,11050.0,2026-01-04 00:00:00,20014,3119,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
35,41056,250,11300.0,2026-01-04 00:00:00,20014,3112,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
36,41057,200,11500.0,2026-01-04 00:00:00,20014,3117,2273,COMPRA_ACCION,NaN,NaN,NaN,NaN
37,41058,140.0,11640.0,2026-01-04 00:00:00,20014,3116,2273,ABONO_PRESTAMO,6845,15.0,125.0,NaN
38,41059,-10000.0,1640.0,2026-01-04 00:00:00,20014,3106,2273,ENTREGA_PRESTAMO,6846,NaN,NaN,NaN
39,41060,20.0,1660.0,2026-01-04 00:00:00,20014,3110,2273,PAGO_MULTA,NaN,NaN,NaN,3682.0
40,41061,20.0,1680.0,2026-01-04 00:00:00,20014,3111,2273,PAGO_MULTA,NaN,NaN,NaN,3683.0
41,41062,20.0,1700.0,2026-01-04 00:00:00,20014,3115,2273,PAGO_MULTA,NaN,NaN,NaN,3684.0
42,41063,20.0,1720.0,2026-01-04 00:00:00,20014,3118,2273,PAGO_MULTA,NaN,NaN,NaN,3685.0