In [1]:
from cosecha_colectiva import miscelaneous as m
import pandas as pd
m.try_find_conf_file()


from cosecha_colectiva import main_tester as mt
from cosecha_colectiva import config
from cosecha_colectiva import query_cosecha as qc
from cosecha_colectiva import test_cosecha_api as tca
from cosecha_colectiva import CAF_DB_Monitor as CDM

from cosecha_colectiva import miscelaneous as m



import logging
import pathlib
from datetime import datetime, date
from dateutil.relativedelta import relativedelta

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)

Local configuration file found !!, no need to run the configuration (unless configuration has changed)

c:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\.venv\Lib\site-packages\datajoint\plugin.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-04-21 10:48:55,181][INFO]: DataJoint 0.14.6 connected to root@junction.proxy.rlwy.net:19994

In [2]:
now = datetime.now()
log_date = now.strftime("%Y-%m-%d_%H_%M_%S")
log_file = pathlib.Path(config.log_dir, log_date+'CreacionGrupo.log')
logging.basicConfig(filename=log_file, encoding='utf-8', level=logging.INFO)

In [3]:
xls_name = 'Verde_Futuro_Test.xlsx'
xls_name = 'Verde_Futuro.xlsx'

xls_name = 'Tropa Gusgones_2.0.xlsx'
xls_name = 'Tropa Gusgones_2.0_Test.xlsx'

xls_name = 'Alcancía Viva.xlsx'
#xls_name = 'Alcancía Viva Test.xlsx'

xls_name = 'Licenciados_Asociados.xlsx'
#xls_name = 'Licenciados_Asociados_Test.xlsx'

xls_name = 'Juntas_ahorramos.xlsx'
xls_name = 'Juntes_ahorramos.xlsx'


xls_name = 'Procoseq.xlsx'

xls_name = 'CAFAM.xlsx'

xls_name = 'La Colmena.xlsx'

xls_name = 'Caja ahorro magueyeros.xlsx'

xls_name = 'Caja la llave.xlsx'

xls_name = 'Agrosemilla sin varo'

xls_name = 'Alcancía Viva.xlsx'

#xls_name = 'Caja llanitos Hidalgo'
#xls_name = 'Juntos_ahorramos.xlsx'



#xls_name = 'CAF_GrupoTest.xlsx'
#xls_name = 'CAF_GrupoHidalgo.xlsx'
#xls_name = 'GrupoCafam.xlsx'

#xls_name = 'Yeiyei'

In [4]:
xls_name

'Alcancía Viva.xlsx'

In [5]:
[id_grupo, grupo_found] = qc.get_grupo_id_by_name(xls_name.replace(".xlsx", ""))
print(id_grupo)
print(grupo_found)
#qc.delete_grupo(id_grupo, solo_sesiones=True)
#qc.delete_grupo(id_grupo)

2574
True

In [6]:
if not grupo_found:
    grupo_data = m.read_caf_excel_sheet(pathlib.Path(xls_name), 'Grupo')
    id_grupo = qc.insert_grupo(grupo_data.to_dict('records'))
    id_grupo = id_grupo['Grupo_id']
    
id_grupo

np.int64(2574)

In [7]:
if not grupo_found:

    socios_xls = pd.DataFrame(m.get_dict_usuarios_xls(xls_name))
    # Solo crea socios cuando viene los datos completos
    if not socios_xls['Fecha_nac'].isna().all():
        print('Creando usuarios')
        tca.CAF_API_group_creation_tester.create_users(xls_name)

    grupo_socio_df = qc.prepare_insert_socio_grupo(xls_name, id_grupo)

    df_acuerdos = m.read_caf_excel_sheet(pathlib.Path(xls_name), "Acuerdos")
    df_acuerdos['Grupo_id'] = id_grupo
    df_acuerdos['Fecha_acuerdos'] = datetime.strftime(date.today(), format='%Y-%m-%d')
    df_acuerdos['Status'] = 1

    df_acuerdos['Id_socio_administrador'] = grupo_socio_df.loc[0,'Socio_id']
    df_acuerdos['Id_socio_administrador_suplente'] = grupo_socio_df.loc[1,'Socio_id']

    qc.insert_acuerdos(df_acuerdos.to_dict('records')[0])

In [8]:
start_month = 1
end_month = 1
last_fecha = qc.get_last_fecha_sesion_grupo(id_grupo)
initial_date = (last_fecha[0]['Fecha'] + relativedelta(months=end_month))
initial_date = (last_fecha[0]['Fecha'] + relativedelta(months=0))
initial_date

datetime.date(2026, 2, 26)

In [10]:
initial_date = date(2026, 3, 16)
initial_date

datetime.date(2026, 3, 16)

In [11]:

monitor_grupo = CDM.CAF_DB_Monitor(id_grupo, xls_name, starting_date=initial_date)
monitor_grupo.socios_acciones

,Grupo_socio_id,Socio_id,Tipo_socio,Status,Acciones,Grupo_id,CURP,xls_order
0,8924,2934,SOCIO,1,630,2574,GUGF040601MQTZRRA6,0
1,8894,2924,SUPLENTE,1,430,2574,AAAA040807MHGZDNA5,1
2,8884,2914,SOCIO,1,470,2574,GUAS020327MTLDVVA0,2
3,8904,2904,SOCIO,1,450,2574,MAOJ890915HQTRLL04,3
4,8914,2894,ADMIN,1,1100,2574,LESC721122HDFNLR05,4

In [12]:
monitor_grupo.sesiones_bd

Empty DataFrame
Columns: [Sesion_id, Fecha, Activa, Caja, Acciones, Ganancias, Fecha_prox_reunion, Lugar_prox_reunion, Tipo_sesion, Grupo_id, created_at]
Index: []

In [13]:
prestamos_activos = monitor_grupo.prestamos.loc[monitor_grupo.prestamos['Estatus_prestamo']==0,:]
prestamos_activos

,Prestamo_id,Acuerdos_id,Monto_prestamo,Monto_pagado,Interes_generado,Interes_pagado,Fecha_inicial,Fecha_final,Estatus_ampliacion,Observaciones,Num_sesiones,Sesiones_restantes,Estatus_prestamo,Socio_id,Sesion_id,Prestamo_original_id,Grupo_id,Tasa_interes,Limite_credito,Creditos_simultaneos,Interes_morosidad,Ampliacion_prestamos,Interes_ampliacion,Mod_calculo_interes,Tasa_interes_prestamo_grande,Grupo_socio_id,Status_socio,interes_futuro,Ultimo_interes_pagado,debe_interes,sobrante_abono,Ultimo_abono
43,6879,2270,200.0,0.0,0.0,0.0,2026-03-07,2026-04-07,0,Préstamo generado en script automático,1,1,0,2894,20074,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8914,1,12.0,0,0,0,0

In [14]:
monitor_grupo.caja

2982.0

In [15]:

for month in range(start_month, end_month+1):

    print('month: ', month)

    try:
        monitor_grupo.actualiza_todo_sesion(xls_name, month, type_xls='NEW', bd_update=True, unique_session_to_update=False)
    except Exception as e:
        print(e)
        raise(e)
        break

month:  1

C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:287: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  prestamos_activos.loc[prestamos_activos['sobrante_abono'] < 0, 'Interes_pagado'] =\
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:294: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  prestamos_activos.loc[prestamos_activos['sobrante_abono'] < 0, 'Ultimo_interes_pagado'] =\
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:311: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[12.0]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  self.prestamos.loc[prestamos_activos.index] = prestamos_activos
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:311: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[12]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.prestamos.loc[prestamos_activos.index] = prestamos_activos
C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:311: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[212.0]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  self.prestamos.loc[prestamos_activos.index] = prestamos_activos

df_prestamos in actualiza prestamos
         PRÉSTAMO AMPLIACIÓN NUM_SESIONES
Socio_id
2934      [200.0]        [0]          [1]
2904      [100.0]        [0]          [1]
2894      [400.0]        [0]          [1]
ganancias_totales_sesion
12.0
ganancias_totales_floor
11.0
sob_acciones
2.0
ganancias_sesion
   Acciones  Socio_id  Monto_ganancia_floor  sobrante_Monto_ganancia  \
0       480      2924                   1.5                      0.5
1       480      2914                   1.5                      0.5
2       490      2904                   1.5                      0.0
3       710      2934                   2.5                      0.0
4      1190      2894                   4.0                      0.0

   Monto_ganancia  Entregada  Sesion_id  Ganancias_id  Ganancia_accion periodo
0             2.0          0      20096         -1000         0.003582   nuevo
1             2.0          0      20096          -999         0.003582   nuevo
2             1.5          0      20096          -998         0.003582   nuevo
3             2.5          0      20096          -997         0.003582   nuevo
4             4.0          0      20096          -996         0.003582   nuevo

C:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\cosecha_colectiva\CAF_DB_Monitor.py:815: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  self.transacciones_bd = pd.concat([self.transacciones_bd, these_transactions], axis=0, ignore_index=True)

In [16]:
monitor_grupo.prestamos

,Prestamo_id,Acuerdos_id,Monto_prestamo,Monto_pagado,Interes_generado,Interes_pagado,Fecha_inicial,Fecha_final,Estatus_ampliacion,Observaciones,Num_sesiones,Sesiones_restantes,Estatus_prestamo,Socio_id,Sesion_id,Prestamo_original_id,Grupo_id,Tasa_interes,Limite_credito,Creditos_simultaneos,Interes_morosidad,Ampliacion_prestamos,Interes_ampliacion,Mod_calculo_interes,Tasa_interes_prestamo_grande,Grupo_socio_id,Status_socio,interes_futuro,Ultimo_interes_pagado,debe_interes,sobrante_abono,Ultimo_abono
0,6523,2204,80.0,80.0,2.5,2.5,2024-12-27,2025-02-27,0,Préstamo generado en script automático,2,1,1,2934,19741,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
1,6524,2204,100.0,100.0,3.0,3.0,2024-12-27,2025-02-27,0,Préstamo generado en script automático,2,1,1,2904,19741,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8904.0,1,0.0,0.0,0,0,0.0
2,6525,2204,100.0,100.0,9.0,9.0,2025-01-27,2025-07-27,0,Préstamo generado en script automático,6,3,1,2914,19742,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8884.0,1,0.0,0.0,0,0,0.0
3,6526,2204,100.0,100.0,6.0,6.0,2025-01-27,2025-07-27,0,Préstamo generado en script automático,6,4,1,2934,19742,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
4,6560,2204,200.0,200.0,12.0,12.0,2025-03-27,2025-08-27,0,,2,0,1,2894,19796,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
5,6561,2204,100.0,100.0,3.0,3.0,2025-03-27,2025-08-27,0,,2,1,1,2924,19797,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8894.0,1,0.0,0.0,0,0,0.0
6,6562,2204,200.0,200.0,6.0,6.0,2025-03-27,2025-08-27,0,,1,0,1,2904,19797,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8904.0,1,0.0,0.0,0,0,0.0
7,6585,2204,100.0,100.0,3.0,3.0,2025-05-01,2025-10-01,0,,1,0,1,2914,19817,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8884.0,1,0.0,0.0,0,0,0.0
8,6586,2204,100.0,100.0,3.0,3.0,2025-05-01,2025-10-01,0,,1,0,1,2924,19817,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8894.0,1,0.0,0.0,0,0,0.0
9,6587,2204,100.0,100.0,3.0,3.0,2025-05-01,2025-10-01,0,,1,0,1,2904,19817,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8904.0,1,0.0,0.0,0,0,0.0
10,6588,2204,200.0,200.0,6.0,6.0,2025-05-01,2025-10-01,0,,1,0,1,2894,19817,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
11,6589,2204,150.0,150.0,4.5,4.5,2025-05-01,2025-10-01,0,,1,0,1,2934,19817,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
12,6597,2204,50.0,50.0,1.5,1.5,2025-06-02,2025-11-02,0,,1,0,1,2914,19841,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8884.0,1,0.0,0.0,0,0,0.0
13,6598,2204,100.0,100.0,3.0,3.0,2025-06-02,2025-11-02,0,,1,0,1,2924,19841,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8894.0,1,0.0,0.0,0,0,0.0
14,6599,2204,200.0,200.0,6.0,6.0,2025-06-02,2025-11-02,0,,1,0,1,2904,19841,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8904.0,1,0.0,0.0,0,0,0.0
15,6600,2204,200.0,200.0,6.0,6.0,2025-06-02,2025-11-02,0,,1,0,1,2894,19841,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
16,6601,2204,250.0,250.0,7.5,7.5,2025-06-02,2025-11-02,0,,1,0,1,2934,19841,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
17,6610,2204,100.0,100.0,3.0,3.0,2025-06-30,2025-11-30,0,,1,0,1,2904,19860,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8904.0,1,0.0,0.0,0,0,0.0
18,6611,2204,300.0,300.0,9.0,9.0,2025-06-30,2025-11-30,0,,1,0,1,2894,19860,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
19,6612,2204,250.0,250.0,7.5,7.5,2025-06-30,2025-11-30,0,,1,0,1,2934,19860,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
20,6613,2204,200.0,200.0,6.0,6.0,2025-06-30,2025-11-30,0,,1,0,1,2914,19860,None,2574,3.0,4,1,1.0,0,NaN,1,0.0,8884.0,1,0.0,0.0,0,0,0.0
21,6638,2270,300.0,300.0,18.0,18.0,2025-07-31,2025-08-30,0,,1,0,1,2904,19878,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8904.0,1,0.0,0.0,0,0,0.0
22,6639,2270,400.0,400.0,48.0,48.0,2025-07-31,2025-09-30,0,,2,0,1,2894,19878,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
23,6640,2270,500.0,500.0,60.0,60.0,2025-07-31,2025-09-30,0,,2,0,1,2934,19878,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
24,6641,2270,250.0,250.0,15.0,15.0,2025-07-31,2025-08-30,0,,1,0,1,2914,19878,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8884.0,1,0.0,0.0,0,0,0.0
25,6642,2270,300.0,300.0,18.0,18.0,2025-07-31,2025-08-30,0,,1,0,1,2924,19878,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8894.0,1,0.0,0.0,0,0,0.0
26,6643,2270,500.0,500.0,60.0,60.0,2025-08-29,2026-01-29,0,,2,0,1,2914,19889,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8884.0,1,0.0,0.0,0,0,0.0
27,6644,2270,300.0,300.0,18.0,18.0,2025-08-29,2026-01-29,0,,1,0,1,2924,19889,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8894.0,1,0.0,0.0,0,0,0.0
28,6645,2270,300.0,300.0,36.0,36.0,2025-08-29,2026-01-29,0,,1,-1,1,2904,19889,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8904.0,1,0.0,0.0,0,0,0.0
29,6654,2270,400.0,400.0,24.0,24.0,2025-09-26,2026-02-26,0,,1,0,1,2894,19894,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
30,6655,2270,200.0,200.0,12.0,12.0,2025-09-26,2026-02-26,0,,1,0,1,2934,19894,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
31,6674,2270,550.0,550.0,33.0,33.0,2025-10-30,2026-03-30,0,,2,1,1,2914,19911,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8884.0,1,0.0,0.0,0,0,0.0
32,6675,2270,300.0,300.0,18.0,18.0,2025-10-30,2026-03-30,0,,1,0,1,2904,19911,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8904.0,1,0.0,0.0,0,0,0.0
33,6676,2270,500.0,500.0,30.0,30.0,2025-10-30,2026-03-30,0,,2,1,1,2894,19911,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
34,6677,2270,300.0,300.0,18.0,18.0,2025-10-30,2026-03-30,0,,1,0,1,2934,19911,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
35,6695,2270,600.0,600.0,36.0,36.0,2025-11-27,2026-04-27,0,,2,1,1,2914,19923,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8884.0,1,0.0,0.0,0,0,0.0
36,6696,2270,100.0,100.0,6.0,6.0,2025-11-27,2026-04-27,0,,2,1,1,2924,19923,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8894.0,1,0.0,0.0,0,0,0.0
37,6697,2270,300.0,300.0,18.0,18.0,2025-11-27,2026-04-27,0,,2,1,1,2904,19923,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8904.0,1,0.0,0.0,0,0,0.0
38,6698,2270,600.0,600.0,36.0,36.0,2025-11-27,2026-04-27,0,,2,1,1,2894,19923,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
39,6699,2270,800.0,800.0,48.0,48.0,2025-11-27,2026-04-27,0,,2,1,1,2934,19923,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
40,6827,2270,600.0,600.0,36.0,36.0,2026-01-29,2026-06-29,0,,1,0,1,2914,19968,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8884.0,1,0.0,0.0,0,0,0.0
41,6828,2270,500.0,500.0,30.0,30.0,2026-01-29,2026-06-29,0,,1,0,1,2894,19968,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
42,6829,2270,500.0,500.0,30.0,30.0,2026-01-29,2026-06-29,0,,1,0,1,2934,19968,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8924.0,1,0.0,0.0,0,0,0.0
43,6879,2270,200.0,200.0,12.0,12.0,2026-03-07,2026-04-07,0,Préstamo generado en script automático,1,0,1,2894,20074,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,8914.0,1,0.0,0.0,0,0,0.0
44,6892,2270,200.0,0.0,0.0,0,2026-03-16,2026-04-16,0,Préstamo generado en script automático,1,1,0,2934,20096,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,NaN,1,12.0,0,0,0,0
45,6893,2270,100.0,0.0,0.0,0,2026-03-16,2026-04-16,0,Préstamo generado en script automático,1,1,0,2904,20096,None,2574,6.0,4,1,2.0,0,NaN,1,0.0,NaN,1,6.0,0,0,0,0
46,6894,2270,400.0,0.0,0.0,0,2026-03-16,2026-04-16,0,Préstamo generado en script automático,1,1,0,2894,20096,None,2574,6.0,4,1,2.0,0,None,1,0.0,NaN,1,24.0,0,0,0,0

In [17]:
monitor_grupo.caja

np.float64(2764.0)

In [18]:
monitor_grupo.multas

,Multa_id,Monto_multa,Descripcion,Status,Sesion_id,Socio_id,Transaccion_id,created_at,Pago_en_sesion
0,3539,5.0,Multa # 1 socio 2894 grupo: 2574 con script,1,19741,2894,39501,2024-12-27 00:00:00,0
1,3570,20.0,Falta justificada,1,19797,2914,39471,2025-03-27 21:36:52,0
2,3571,20.0,Falta justificada,1,19797,2934,39472,2025-03-27 21:37:10,0
3,3589,7.0,Retraso de inicio,1,19860,2924,39833,2025-06-30 19:15:55,0
4,3601,15.0,15 pesos por retraso,1,19889,2934,39905,2025-08-29 20:28:14,0
5,3608,20.0,falta justificada,1,19894,2914,40054,2025-09-26 20:12:51,0
6,3698,4.0,Multa # 1 socio 2934 grupo: 2574 con script,0,20096,2934,None,2026-03-16 00:00:00,0

In [19]:
monitor_grupo.ganancias

,Ganancias_id,Ganancia_accion,Monto_ganancia,Entregada,Socio_id,Sesion_id,periodo
0,79667,0.000000,0.0,1,2934,19741,nuevo
1,79668,0.000000,0.0,1,2924,19741,nuevo
2,79669,0.000000,0.0,1,2914,19741,nuevo
3,79670,0.000000,0.0,1,2904,19741,nuevo
4,79671,0.000000,0.0,1,2894,19741,nuevo
...,...,...,...,...,...,...,...
70,81439,0.003582,2.0,0,2924,20096,nuevo
71,81440,0.003582,2.0,0,2914,20096,nuevo
72,81441,0.003582,1.5,0,2904,20096,nuevo
73,81442,0.003582,2.5,0,2934,20096,nuevo
74,81443,0.003582,4.0,0,2894,20096,nuevo

In [20]:
monitor_grupo.multas

,Multa_id,Monto_multa,Descripcion,Status,Sesion_id,Socio_id,Transaccion_id,created_at,Pago_en_sesion
0,3539,5.0,Multa # 1 socio 2894 grupo: 2574 con script,1,19741,2894,39501,2024-12-27 00:00:00,0
1,3570,20.0,Falta justificada,1,19797,2914,39471,2025-03-27 21:36:52,0
2,3571,20.0,Falta justificada,1,19797,2934,39472,2025-03-27 21:37:10,0
3,3589,7.0,Retraso de inicio,1,19860,2924,39833,2025-06-30 19:15:55,0
4,3601,15.0,15 pesos por retraso,1,19889,2934,39905,2025-08-29 20:28:14,0
5,3608,20.0,falta justificada,1,19894,2914,40054,2025-09-26 20:12:51,0
6,3698,4.0,Multa # 1 socio 2934 grupo: 2574 con script,0,20096,2934,None,2026-03-16 00:00:00,0

In [18]:
monitor_grupo.acuerdos

Acuerdo_id                                      2270
Id_temporal_admin                               None
id_treasurer_user                               None
id_secretary_user                               None
allow_action_retreat_on_normal_session             0
Grupo_id                                        2574
Fecha_acuerdos                            2025-07-01
Fecha_acuerdos_fin                        2026-02-01
Status                                             1
Periodo_reuniones                                  3
Periodo_cargos                                     1
Limite_inasistencias                               3
Minimo_aportacion                                100
Costo_acciones                                    10
Tasa_interes                                     6.0
Limite_credito                                     4
Porcentaje_fondo_comun                             0
Creditos_simultaneos                               1
Interes_morosidad                                2.0
Ampliacion_prestamos                               0
Interes_ampliacion                              None
Mod_calculo_interes                                1
Tasa_interes_prestamo_grande                     0.0
Id_socio_administrador                          2894
Id_socio_administrador_suplente                 2924
dtype: object

In [19]:
monitor_grupo.ganancias_acum.sum()

Monto_ganancia    96.0
dtype: float64

In [20]:
monitor_grupo.multas

,Multa_id,Monto_multa,Descripcion,Status,Sesion_id,Socio_id,Transaccion_id,created_at,Pago_en_sesion
0,3539,5.0,Multa # 1 socio 2894 grupo: 2574 con script,1,19741,2894,39501,2024-12-27 00:00:00,0
1,3570,20.0,Falta justificada,1,19797,2914,39471,2025-03-27 21:36:52,0
2,3571,20.0,Falta justificada,1,19797,2934,39472,2025-03-27 21:37:10,0
3,3589,7.0,Retraso de inicio,1,19860,2924,39833,2025-06-30 19:15:55,0
4,3601,15.0,15 pesos por retraso,1,19889,2934,39905,2025-08-29 20:28:14,0
5,3608,20.0,falta justificada,1,19894,2914,40054,2025-09-26 20:12:51,0

In [21]:
monitor_grupo.transacciones_prestamo_bd

,index,Transaccion_prestamo_id,Prestamo_id,Transaccion_id,Monto_abono_prestamo,Monto_abono_interes
0,0,11316,6827,41325,600.0,36
1,1,11317,6828,41326,500.0,30
2,2,11318,6829,41327,500.0,30

In [22]:
monitor_grupo.transacciones_bd

,Transaccion_id,Cantidad_movimiento,Caja,Timestamp,Sesion_id,Socio_id,Acuerdo_id,Catalogo_id,Prestamo_id,Ultimo_interes_pagado,sobrante_abono
0,41320,60,60,2026-03-07 00:00:00,20074,2934,2270,COMPRA_ACCION,NaN,NaN,NaN
1,41321,100,160,2026-03-07 00:00:00,20074,2924,2270,COMPRA_ACCION,NaN,NaN,NaN
2,41322,100,260,2026-03-07 00:00:00,20074,2914,2270,COMPRA_ACCION,NaN,NaN,NaN
3,41323,50,310,2026-03-07 00:00:00,20074,2904,2270,COMPRA_ACCION,NaN,NaN,NaN
4,41324,50,360,2026-03-07 00:00:00,20074,2894,2270,COMPRA_ACCION,NaN,NaN,NaN
5,41325,636.0,996.0,2026-03-07 00:00:00,20074,2914,2270,ABONO_PRESTAMO,6827.0,36,600.0
6,41326,530.0,1526.0,2026-03-07 00:00:00,20074,2894,2270,ABONO_PRESTAMO,6828.0,30,500.0
7,41327,530.0,2056.0,2026-03-07 00:00:00,20074,2934,2270,ABONO_PRESTAMO,6829.0,30,500.0
8,41328,-200.0,1856.0,2026-03-07 00:00:00,20074,2894,2270,ENTREGA_PRESTAMO,6879.0,NaN,NaN