In [ ]:
from cosecha_colectiva import miscelaneous as m
m.try_find_conf_file()

import datajoint as dj

from cosecha_colectiva import main_tester as mt
from cosecha_colectiva import query_cosecha as qc
from cosecha_colectiva import config
from cosecha_colectiva import CAF_DB_Monitor as CDM
from cosecha_colectiva import test_cosecha_api as tca

import logging
import pathlib
from datetime import datetime
import pandas as pd

Local configuration file found !!, no need to run the configuration (unless configuration has changed)

c:\Users\luna_\Documents\PersonalProjects\cosecha_colectiva_tester\.venv\Lib\site-packages\datajoint\plugin.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
[2026-05-13 16:02:22,469][INFO]: DataJoint 0.14.6 connected to cosecha_admin@cosecha-colectiva-db.cs5aiug424nn.us-east-1.rds.amazonaws.com:3306

In [ ]:
import importlib

importlib.reload(config)
importlib.reload(tca)
importlib.reload(qc)
importlib.reload(CDM)
importlib.reload(mt)

In [ ]:
#xls_name = 'CAF_GrupoTesteador.xlsx'
xls_name = 'CAF_GrupoAstronomo.xlsx'
xls_name = 'CAF_GrupoMesero.xlsx'
#xls_name = 'CAF_GrupoDomador.xlsx'
#xls_name = 'CAF_GrupoCafam.xlsx'
#xls_name = 'GrupoCafam.xlsx'
#xls_name = 'CAF_GrupoHidalgo.xlsx'
#xls_name = 'CAF_GrupoCalcetin.xlsx'
#xls_name = 'Alcancía Viva'
xls_name = 'Caja Cadereyta.xlsx'

In [ ]:
cosecha_db = dj.create_virtual_module(config.db_name, config.db_name)

In [67]:
id_grupo, grupo_found = qc.get_grupo_id_by_name(xls_name.split('.')[0])
print(id_grupo)

2657

In [68]:
qc.delete_grupo(id_grupo, solo_sesiones=True, conservar_acuerdos=True, force_delete=True)

([], 'transaccion_prestamos')
([{'Transaccion_id': np.int64(40238)}, {'Transaccion_id': np.int64(40239)}, {'Transaccion_id': np.int64(40240)}, {'Transaccion_id': np.int64(40241)}, {'Transaccion_id': np.int64(40242)}, {'Transaccion_id': np.int64(40243)}, {'Transaccion_id': np.int64(40244)}, {'Transaccion_id': np.int64(40245)}, {'Transaccion_id': np.int64(40246)}, {'Transaccion_id': np.int64(40247)}], 'transacciones')
DELETE from cosecha.transacciones WHERE Transaccion_id in (40238, 40239, 40240, 40241, 40242, 40243, 40244, 40245, 40246, 40247)
([], 'interes_prestamo')
([{'Ganancias_id': np.int64(80429)}, {'Ganancias_id': np.int64(80430)}, {'Ganancias_id': np.int64(80431)}, {'Ganancias_id': np.int64(80432)}, {'Ganancias_id': np.int64(80433)}, {'Ganancias_id': np.int64(80434)}, {'Ganancias_id': np.int64(80435)}, {'Ganancias_id': np.int64(80436)}, {'Ganancias_id': np.int64(80437)}, {'Ganancias_id': np.int64(80438)}], 'ganancias')
DELETE from cosecha.ganancias WHERE Ganancias_id in (80429, 80430, 80431, 80432, 80433, 80434, 80435, 80436, 80437, 80438)
([], 'multas')
([], 'prestamos')
([], 'prestamos')
([{'Asistencia_id': np.int64(139002)}, {'Asistencia_id': np.int64(139003)}, {'Asistencia_id': np.int64(139004)}, {'Asistencia_id': np.int64(139005)}, {'Asistencia_id': np.int64(139006)}, {'Asistencia_id': np.int64(139007)}, {'Asistencia_id': np.int64(139008)}, {'Asistencia_id': np.int64(139009)}, {'Asistencia_id': np.int64(139010)}, {'Asistencia_id': np.int64(139011)}], 'asistencias')
DELETE from cosecha.asistencias WHERE Asistencia_id in (139002, 139003, 139004, 139005, 139006, 139007, 139008, 139009, 139010, 139011)
([{'Sesion_id': np.int64(19929)}], 'sesiones')
DELETE from cosecha.sesiones WHERE Sesion_id in (19929)
([], 'acuerdos')

In [69]:
now = datetime.now()
log_date = now.strftime("%Y-%m-%d_%H_%M_%S")
log_file = pathlib.Path(config.log_dir, log_date+'_Sesiones.log')
log_file
logging.basicConfig(filename=log_file, encoding='utf-8', level=logging.INFO)

In [70]:
# tca.CAF_API_sessions_tester.poner_corriente_grupo(xls_name)

In [71]:
monitor_grupo = CDM.CAF_DB_Monitor(id_grupo, xls_name)

In [72]:
monitor_grupo.limite_credito_socios

,Grupo_socio_id,Socio_id,Tipo_socio,Status,Acciones,Grupo_id,unique_key,CURP,xls_order,monto_total,num_prestamos,Limite_credito_final,Limite_credito_teorico,puede_pedir_prestamo
0,9234,3117,ADMIN,1,100,2657,3117_2657,TOLL770222MMSJNR01,0,0,0,2000,2000,True
1,9235,3118,ADMIN,1,100,2657,3118_2657,TOLL770222MMSJNR02,1,0,0,2000,2000,True
2,9236,3119,SOCIO,1,100,2657,3119_2657,TOLL770222MMSJNR03,2,0,0,2000,2000,True
3,9237,3120,SOCIO,1,100,2657,3120_2657,TOLL770222MMSJNR04,3,0,0,2000,2000,True
4,9238,3121,SOCIO,1,100,2657,3121_2657,TOLL770222MMSJNR05,4,0,0,2000,2000,True
5,9239,3122,SOCIO,1,100,2657,3122_2657,TOLL770222MMSJNR06,5,0,0,2000,2000,True
6,9240,3123,SOCIO,1,100,2657,3123_2657,TOLL770222MMSJNR07,6,0,0,2000,2000,True
7,9241,3124,SOCIO,1,100,2657,3124_2657,TOLL770222MMSJNR08,7,0,0,2000,2000,True
8,9242,3125,SOCIO,1,100,2657,3125_2657,TOLL770222MMSJNR09,8,0,0,2000,2000,True
9,9243,3126,SOCIO,1,100,2657,3126_2657,TOLL770222MMSJNR10,9,0,0,2000,2000,True

In [75]:
start_month = 2
end_month = 2

for month in range(start_month, end_month+1):

    print('month: ', month)

    try:
        monitor_grupo.actualiza_todo_sesion(xls_name, month, type_xls='NEW')
    except Exception as e:
        print(e)
        raise(e)
    try:
        mt.test_sesion_months(xls_name, month, month, type_xls='NEW', id_grupo=id_grupo)
    except Exception as e:
        print(e)
        raise(e)
    [status, dfs] = monitor_grupo.compara_db_monitor()
    if not status:
        print('Algo no coincidió')
        break

month:  2
df_prestamos in actualiza prestamos
         PRÉSTAMO AMPLIACIÓN NUM_SESIONES
Socio_id
3121      [500.0]        [0]          [4]
ganancias_totales_sesion
0
ganancias_totales_floor
0.0
sob_acciones
0.0
payload {"username": "Troll1", "password": "12345"}
<Response [200]>
{'groups': [{'Grupo_id': 2657, 'Nombre_grupo': 'CAF_GrupoTroll', 'Rol_socio': 'ADMIN', 'Status': 'ACTIVE', 'Miembros_Totales': 10, 'Miembros_Activos': 10, 'previousSesion': '2026-05-13', 'nextSesion': None}]}
payload {"username": "Troll1", "password": "12345"}
<Response [200]>
create_session fun
socios_dict [{'Socio_id': np.int64(3117)}, {'Socio_id': np.int64(3118)}, {'Socio_id': np.int64(3119)}, {'Socio_id': np.int64(3120)}, {'Socio_id': np.int64(3121)}, {'Socio_id': np.int64(3122)}, {'Socio_id': np.int64(3123)}, {'Socio_id': np.int64(3124)}, {'Socio_id': np.int64(3125)}, {'Socio_id': np.int64(3126)}]
url_crear_sesion aqui .....
{'sessionType': 1, 'sessionId': 19931}
<Response [200]>
{"sessionType": 1, "sessionId": 19931}
id_grupo 2657
prestamos No coinciden monitor y db
Algo no coincidió

In [ ]:
dfs[0].compare(dfs[1])

  Fecha_inicial             Fecha_final              \
           self       other        self       other
0    2026-05-13  2026-06-13        None  2026-10-13

                     Observaciones
                              self                                   other
0  Prestamo socio 3121 grupo: 2657  Préstamo generado en script automático

:

In [13]:
monitor_grupo.prestamos.loc[0,:]

Prestamo_id                      6169
Monto_prestamo                  500.0
Monto_pagado                     29.0
Interes_generado                 39.5
Interes_pagado                   30.0
Estatus_ampliacion              False
Num_sesiones                        6
Sesiones_restantes                  2
Estatus_prestamo                    0
Socio_id                         1234
Sesion_id                       19488
Acuerdos_id                      2044
Prestamo_original_id             None
Grupo_id                         2394
Tasa_interes                      2.0
Limite_credito                     20
Creditos_simultaneos                2
Interes_morosidad                 1.5
Ampliacion_prestamos                1
Interes_ampliacion                1.5
Mod_calculo_interes                 0
Tasa_interes_prestamo_grande      1.5
interes_futuro                    9.5
Ultimo_interes_pagado               0
debe_interes                      9.5
sobrante_abono                    NaN
Ultimo_abono                      NaN
Status_socio                        1
Name: 0, dtype: object

In [14]:
monitor_grupo.interes_prestamo

   Interes_prestamo_id Prestamo_id  Sesion_id  Monto_interes  Tipo_interes
0               103148        6169      19489           10.0             0
1               103149        6170      19490           10.0             0
2               103150        6169      19490           10.0             0
3               103151        6170      19491           10.0             0
4               103152        6169      19491           10.0             0
5               103153        6170      19492            8.0             0
6               103154        6169      19492            9.5             0

In [15]:
dfs

[]

In [19]:
monitor_grupo.ganancias.groupby('Socio_id').sum()

          Ganancias_id  Monto_ganancia  Entregada  Sesion_id
Socio_id
1194            461494             6.5          1     113394
1204            461509             6.5          1     113394
1214            461524             6.5          1     113394
1224            461539             6.5          1     113394
1234            461554             6.0          1     113394
1244            461569             6.0          1     113394
1254            461584             5.5          1     113394
1264            461599             5.5          1     113394
1274            461614             4.5          1     113394
1284            461629             4.5          1     113394

In [16]:
monitor_grupo.sesiones

[{'Sesion_id': 15944},
 {'Sesion_id': 19488},
 {'Sesion_id': 19489},
 {'Sesion_id': 19490},
 {'Sesion_id': 19491},
 {'Sesion_id': 19492}]

In [22]:
118.75+9.5

128.25

In [26]:
161.5-9.5

152.0

In [27]:
475/152

3.125

In [25]:
475/4+9.5

128.25

In [12]:
monitor_grupo.socios_acciones.loc[monitor_grupo.socios_acciones['Socio_id'] == 1324, 'Status'].values[0]

1

In [10]:
comp = dfs[0].compare(dfs[1])
comp

   Monto_ganancia
             self     other
24           1.25  1.428571
25           1.25  1.428571
26           1.25  1.428571
27           1.25  1.428571
28           1.25  1.428571
29           1.25  1.428571
30           1.25  1.428571

In [19]:
monitor_grupo.ganancias

    Ganancias_id  Monto_ganancia  Entregada  Socio_id  Sesion_id
0          49264        0.000000          0      1324       6994
1          49274        0.000000          0      1334       6994
2          49284        0.000000          0      1344       6994
3          49294        0.000000          0      1354       6994
4          49304        0.000000          0      1364       6994
5          49314        0.000000          0      1374       6994
6          49324        0.000000          0      1384       6994
7          49334        0.000000          0      1394       6994
8          52324        0.000000          0      1324       7434
9          52334        0.000000          0      1334       7434
10         52344        0.000000          0      1344       7434
11         52354        0.000000          0      1354       7434
12         52364        0.000000          0      1364       7434
13         52374        0.000000          0      1374       7434
14         52384        0.000000          0      1384       7434
15         52394        0.000000          0      1394       7434
16         52404        1.250000          0      1324       7444
17         52414        1.250000          0      1334       7444
18         52424        1.250000          0      1344       7444
19         52434        1.250000          0      1354       7444
20         52444        1.250000          0      1364       7444
21         52454        1.250000          0      1374       7444
22         52464        1.250000          0      1384       7444
23         52474        1.250000          0      1394       7444
24         52484        1.428571          0      1324       7454
25         52494        1.428571          0      1334       7454
26         52504        1.428571          0      1344       7454
27         52514        1.428571          0      1354       7454
28         52524        1.428571          0      1364       7454
29         52534        1.428571          0      1374       7454
30         52544        1.428571          0      1394       7454

In [ ]:
monitor_grupo

In [18]:
monitor_grupo.multas

,Multa_id,Monto_multa,Descripcion,Status,Sesion_id,Socio_id,Pago_en_sesion
0,1524,10.0,Multa # 1 socio 1534 grupo: 1574,1,7114,1534,0
1,1534,10.0,Multa # 1 socio 1584 grupo: 1574,1,7114,1584,0
2,1544,20.0,Multa # 1 socio 1614 grupo: 1574,1,7134,1614,0

In [22]:
monitor_grupo.prestamos

,Prestamo_id,Monto_prestamo,Monto_pagado,Interes_generado,Interes_pagado,Estatus_ampliacion,Num_sesiones,Sesiones_restantes,Estatus_prestamo,Socio_id,...,Interes_morosidad,Ampliacion_prestamos,Interes_ampliacion,Mod_calculo_interes,Tasa_interes_prestamo_grande,interes_futuro,Ultimo_interes_pagado,debe_interes,sobrante_abono,Ultimo_abono
0,2894,1000.0,1000.0,60.0,60.0,False,6,3,1,1574,...,0.0,0,None,1,1.5,0.0,0,0,0,0
1,2904,600.0,400.0,36.0,24.0,False,6,3,0,1524,...,0.0,0,None,1,1.5,12.0,12.0,12.0,200.0,212.0
2,2914,590.0,400.4,35.4,23.6,False,6,3,0,1554,...,0.0,0,None,1,1.5,11.8,11.8,11.8,200.2,212.0
3,2924,590.0,400.4,35.4,23.6,False,6,3,0,1604,...,0.0,0,None,1,1.5,11.8,11.8,11.8,200.2,212.0
4,2934,675.0,225.5,27.0,13.5,False,6,4,0,1544,...,0.0,0,None,1,1.5,13.5,13.5,13.5,225.5,239.0
5,2944,675.0,225.5,27.0,13.5,False,6,4,0,1564,...,0.0,0,None,1,1.5,13.5,13.5,13.5,225.5,239.0
6,2954,675.0,225.5,27.0,13.5,False,6,4,0,1584,...,0.0,0,None,1,1.5,13.5,13.5,13.5,225.5,239.0
7,2964,675.0,225.5,27.0,13.5,False,6,4,0,1594,...,0.0,0,None,1,1.5,13.5,13.5,13.5,225.5,239.0
8,2974,1000.0,0,20.0,0,False,6,5,0,1534,...,0.0,0,None,1,1.5,20.0,0,0,0,0
9,2984,1200.0,0,24.0,0,False,6,5,0,1574,...,0.0,0,None,1,1.5,24.0,0,0,0,0

In [19]:
monitor_grupo.ganancias

    Ganancias_id  Monto_ganancia  Entregada  Socio_id  Sesion_id
0          49504        0.000000          0      1524       7034
1          49514        0.000000          0      1534       7034
2          49524        0.000000          0      1544       7034
3          49534        0.000000          0      1554       7034
4          49544        0.000000          0      1564       7034
5          49554        0.000000          0      1574       7034
6          49564        0.000000          0      1584       7034
7          49574        0.000000          0      1594       7034
8          49584        0.000000          0      1604       7034
9          49594        0.000000          0      1614       7034
10         50104        2.000000          0      1524       7114
11         50114        2.000000          0      1534       7114
12         50124        2.000000          0      1544       7114
13         50134        2.000000          0      1554       7114
14         50144        2.000000          0      1564       7114
15         50154        2.000000          0      1574       7114
16         50164        2.000000          0      1584       7114
17         50174        2.000000          0      1594       7114
18         50184        2.000000          0      1604       7114
19         50194        2.000000          0      1614       7114
20         50204        2.500000          0      1524       7124
21         50214        1.666667          0      1534       7124
22         50224        2.500000          0      1544       7124
23         50234        1.666667          0      1554       7124
24         50244        1.666667          0      1564       7124
25         50254        2.500000          0      1574       7124
26         50264        2.500000          0      1584       7124
27         50274        2.500000          0      1594       7124
28         50284        1.666667          0      1604       7124
29         50294        0.833333          0      1614       7124
30         50304        8.297561          0      1524       7134
31         50314        7.375610          0      1534       7134
32         50324        9.219512          0      1544       7134
33         50334        5.531707          0      1554       7134
34         50344        6.453659          0      1564       7134
35         50354        9.219512          0      1574       7134
36         50364        9.219512          0      1584       7134
37         50374        9.219512          0      1594       7134
38         50384        7.375610          0      1604       7134
39         50394        3.687805          0      1614       7134
40         50404       12.608850          0      1524       7144
41         50414       11.638938          0      1534       7144
42         50424       11.638938          0      1544       7144
43         50434        7.759292          0      1554       7144
44         50444       10.669027          0      1564       7144
45         50454       13.578761          0      1574       7144
46         50464       13.578761          0      1584       7144
47         50474       11.638938          0      1594       7144
48         50484       10.669027          0      1604       7144
49         50494        5.819469          0      1614       7144

In [13]:
monitor_grupo.sesiones

[{'Sesion_id': 2174},
 {'Sesion_id': 6224},
 {'Sesion_id': 6234},
 {'Sesion_id': 6244},
 {'Sesion_id': 6254},
 {'Sesion_id': 6264},
 {'Sesion_id': 6274},
 {'Sesion_id': 6284},
 {'Sesion_id': 6294},
 {'Sesion_id': 6304}]

In [21]:
monitor_grupo.ganancias.groupby('Sesion_id').sum()

           Ganancias_id  Monto_ganancia  Entregada  Socio_id
Sesion_id
6994             394392             0.0          0     10872
7434             418872             0.0          0     10872
7444             419512            10.0          0     10872
7454             367598            10.0          0      9488